### ISSUE TITLE
Title and numbers are cut off in the email

### ISSUE THREAD

**Issue by hshugaleeva** [zebrunner/zebrunner#1619]
1. Send 30 DAYS TOTAL widget by email 
2. Open the email and look attachment

Result: Title and numbers are cut off

![General dashboard - 30 DAYS TOTAL widget](https://user-images.githubusercontent.com/36439738/59513045-abe19c80-8ec2-11e9-8061-9a90cb05f581.png)

**Comment by hshugaleeva** [comment]
@Boniara graph is cut off on the dashboard too http://prntscr.com/o19ks4

macbook pro 13''

**Comment by hursevich** [comment]
We still need optimization of widgets legend.

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.3.0.480-SNAPSHOT server: 1.3.0.713-SNAPSHOT.
