### ISSUE TITLE
Locale and language for test run should be displayed at test runs list view

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#1777]
we already register locale and language in test_configs table but we never show this data on Zafira UI.
Let's find a way to show it somehow on test runs. ideally I see it as optional column which can be shown/hided by each user

**UPD 11-15-2019:**
We'll need to design new UI element allowing to select what columns will be displayed for test runs list view. In scope of this ticket we'll need to provide both language and locale as 2 separate test run attributes (where available - it can be empty in some cases)
@hursevich we'll need to design new design elements.

**Comment by tsvrko** [comment]
looks like ui task

**Comment by nsidorevich** [comment]
@vdelendik in some cases i can see that we have empty language. Can locale be different from language? 
@hursevich where exactly on test runs UI we'd like to see this information?

**Comment by nsidorevich** [comment]
We'll need to design new UI element allowing to select what columns will be displayed for test runs list view. In scope of this ticket we'll need to provide both **language** and **locale** as 2 separate test run attributes (where available - it can be empty in some cases)
@hursevich we'll need to design new design elements.

**Comment by nsidorevich** [comment]
I did a quick research for this one and we are actually returning this info from API already, so the only thing we need at this point is UI element like 
![image](https://user-images.githubusercontent.com/8956214/69052686-b1ff1a80-0a18-11ea-9108-945cf7d76490.png)
allowing user to select which test runs attributes should be displayed and that's it.

Proof:
![image](https://user-images.githubusercontent.com/8956214/69052549-5a60af00-0a18-11ea-8a0f-47ad1944a249.png)

**Comment by lmikhadyuk** [comment]
Already implemented in Zebrunner.
