### ISSUE TITLE
General board widgets have unused JOB_NAME filter enabled

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#1788]
![image](https://user-images.githubusercontent.com/4551455/66700503-b76e9400-ecf9-11e9-8960-fba3417a0ef0.png)

**Comment by nsidorevich** [comment]
Duplicates #1665, closing older one.
@vdelendik could you please add desired behavior?

**Comment by vdelendik** [comment]
JOB_NAME as enabled parameter appeared due to the inconsistency with params and labels...
By default after installing fresh system it should be disabled and located among "SHOW MORE" filters

**Comment by lmikhadyuk** [comment]
Unable to reproduce in ui: 1.405-SNAPSHOT server: 1.593-SNAPSHOT client: 1.0-SNAPSHOT.
