### ISSUE TITLE
test run with 0 executed tests has "in progress" status forever

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#1873]
**Description**
Some TestNG classes have dynamic dataprovider and due to the different reasons could execute 0 tests. All those runs have running state forever without ability to abort correctly.

We have to adjust logic for finish to mark those runs as failed due to the 0 executions and setp appropriate final state. Also if we have 0-0-0 tests registered for in progress job we should be able to abort this run s as well.

**Steps to reproduce**
register test run with completely excluded methods

**Comment by DmitryMishin** [comment]
fixed from v. `1.1.0.434-SNAPSHOT`
