### ISSUE TITLE
On adding github enterprise via DB insert query, when run via testlauncher scan. It still shows old url.

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/zebrunner#195]
1. Add github enterprise via DB insert query.
2. Goto zebrunner test runs > test launcher > select the added repository 
3. Click on scan button.
4. verify test run logs for Jenkins > organization >RegisterRepository >latest run.
   GITHUB_HOST = still picks the old value as (github.com) instead of github enterprise host.

It should pick the latest Github enterprise host.

**Comment by vdelendik** [comment]
issue will be fixed in scope of https://github.com/qaprosoft/qps-infra/issues/227 ticket. New zebrunner insights reporting has possibility to define valid enterprise github url so test launcher UI works correctly

**Comment by vdelendik** [comment]
it should be fixed.

**Comment by okamara** [comment]
Will be verified by Vadim.
