### ISSUE TITLE
It is possible to launch test run with disconnected / red test env provider

### ISSUE THREAD

**Issue by nsidorevich** [zebrunner/zebrunner#1961]
**Description**
Even when test environment provider integration is red it is still possible to launch test run

**Steps to reproduce**
[Make sure to specify user role used to log in to Zafira]
Below are the steps to reproduce the behavior:
1. Go to integrations and use invalid credentials for Zebrunner integration to make it red (disconnected)
2. Go to test run and run a new one via Launcher that should use that integration (e.g. API tests with Zebrunner as test env provider)

**Actual behavior**
Launcher runs new test run

**Expected behavior (if known)**
Launcher should not run new test run and display error instead.

**Environment**
UI version: 1.29
API (back-end) version: 4.1.82

**Additional context**
We need to discuss this before proceed with implementation. We might want to disable "Launch" button on add some kind of indicator to selected runner so user can clearly see if integration is connected or not.

**Comment by brutskov** [comment]
will be available from server v. 1.2.0
