### ISSUE TITLE
Add possibility to search for specific test results by test name or Testrail Id

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/zebrunner#2039]
**Description**
Add possibility to search for specific test results by test name or Testrail Id

**Value**
Often there is a request to show exact results for some specific testcase (or testrail id). And it is a problem to find it if there are more than 100+ tests in a suite. 
It will be really useful to have a search field in run details (as we have for filters) to find required test. 

**Additional context**
And it will be useful to add a possibility to show statistics for specific test cases during period of time.

**Comment by maksimsarychau** [comment]
please increase the priority for this ticket.

**Comment by nsidorevich** [comment]
@hursevich please take a look, guess this one can be included into 1.3 release

**Comment by lmikhadyuk** [comment]
Search by test name already implemented in Zebrunner ui v.1.4.1 | server v.1.4.0.
