### ISSUE TITLE
Blockers icon isn't displayed near test run name after linking blocker issue

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/zebrunner#2062]
**Steps to reproduce**
Below are the steps to reproduce the behavior:
1. Login to Zafira
2. Open test runs tab
3. Open failed test run
4. Click on 3 dots on a failed test
5. Select Link issue
6. Enter jira ID and select blocker checkbox 
7. Click Save
8. Close link issue window

**Actual behavior**
Blockers icon isn't displayed near test run name. only after refreshing the page
<img width="2025" alt="Screen Shot 2020-02-20 at 12 14 32" src="https://user-images.githubusercontent.com/56070333/74919306-71c68400-53db-11ea-8fa9-e40634b4f266.png">

**Expected behavior (if known)**
<img width="2023" alt="Screen Shot 2020-02-20 at 12 14 53" src="https://user-images.githubusercontent.com/56070333/74919318-75f2a180-53db-11ea-96ac-ee0aca512c2e.png">

**Environment**
ui: 1.35.RC2
server: 4.1.88.RC4
client: 4.1.65

**Comment by MitskevichVS** [comment]
Fixed from UI version 1.410-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.413-SNAPSHOT server: 1.597-SNAPSHOT client: 1.0-SNAPSHOT.
