### ISSUE TITLE
Jenkins link is active in slack channel/HTML file 

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/zebrunner#2069]
**Steps to reproduce**
1. Login to Zafira (SuperAdmin)
2. Open integrations tab
3. Enable Slack integration
4. Open test runs tab
5. Run some API tests (for example Carina Demo Tests - API Sample )
6. Open slack channel

**Actual behavior**
Open in Jenkins link is in the slack channel
<img width="1013" alt="Screen Shot 2020-02-26 at 14 24 47" src="https://user-images.githubusercontent.com/56070333/75340768-252fec80-58a4-11ea-89ab-1a44a4b0ca47.png">

OR
1. Login to Zafira
2. Open test runs tab
3. Run some tests
4. Click on 3 dots on test run
5. Select Export to HTML
6. Open dowloaded file
7. Click rebuild 

Actual result: User is redirected on Jenkins page
<img width="1583" alt="Screen Shot 2020-02-26 at 14 40 51" src="https://user-images.githubusercontent.com/56070333/75341987-92448180-58a6-11ea-912b-2fad9ed9ca9b.png">

**Expected behavior (if known)**
Jenkins links should be disabled 

**Environment**
ui: 1.374-SNAPSHOT
server: 1.558-SNAPSHOT
client: 1.0-SNAPSHOT

**Comment by brutskov** [comment]
fixed
will be available in 1.2.0 relase and later
