### ISSUE TITLE
Profile photo disappears after page reloading

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/zebrunner#2072]
**Steps to reproduce**
1. Login ro Zafira
2. Open Account & profile tab
3. Upload profile photo
4. Refresh page

**Actual behavior**
Profile photo disappears

**Expected behavior (if known)**
Profile photo doesn't disappear 

**Environment**
ui: 1.33-SNAPSHOT
server: 1.565-SNAPSHOT
client: 1.0-SNAPSHOT

**Comment by brutskov** [comment]
Will be available in BE 1.1.0.644-SNAPSHOT and later

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.1.0.440-SNAPSHOT server: 1.1.0.647-SNAPSHOT.
