### ISSUE TITLE
Unable to add view

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/zebrunner#2089]
**Steps to reproduce**
1. Login to Zafira (Superadmin)
2. Click on eye on the left panel
3. Click add view

**Actual behavior**
User is not able to add view

**Expected behavior (if known)**
User is able to add view

**Environment**
ui: 1.391-SNAPSHOT
server: 1.584-SNAPSHOT
client: 1.0-SNAPSHOT

**Comment by brutskov** [comment]
View page was fully removed from app
