### ISSUE TITLE
There is no message First/Last name required when create new user

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/zebrunner#2094]
**Description**

**Steps to reproduce**
1. Login to Zafira (Superadmin)
2. Open Users tab
3. Select New User

**Actual behavior**
There is no message First/Last name required .Create button isn't 
<img width="2034" alt="Screen Shot 2020-03-13 at 17 00 01" src="https://user-images.githubusercontent.com/56070333/76627929-f9bc2b80-654c-11ea-9323-45914b5978a4.png">
active

**Environment**
ui: 1.400-SNAPSHOT
server: 4.1.90.RC2
client: 4.1.65

**Comment by MitskevichVS** [comment]
fixed from UI version 1.2.0.450-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.2.0.450-SNAPSHOT server: 1.2.0.673-SNAPSHOT.
