### ISSUE TITLE
Text is shifted on the first login in Safari

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/zebrunner#2095]
**Steps to reproduce**
1. Login to Zafira first time (Safari)

**Actual behavior**
Text is shifted 
<img width="2037" alt="Screen Shot 2020-03-13 at 16 15 00" src="https://user-images.githubusercontent.com/56070333/76629726-ce870b80-654f-11ea-99ff-f6c5e1a63001.png">

**Environment**
Safari  13.0.4 (15608.4.9.1.3)
ui: 1.400-SNAPSHOT
server: 4.1.90.RC2
client: 4.1.65

**Comment by MitskevichVS** [comment]
fixed from UI version 1.404-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Reproducible in Safari on mobile. ui: 1.404-SNAPSHOT server: 4.1.90.RC2 client: 4.1.65
![IMG_8703](https://user-images.githubusercontent.com/56070333/76839173-1ce52480-6846-11ea-9e29-0a08b923c400.PNG)

**Comment by MitskevichVS** [comment]
fixed from UI version 1.404-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.405-SNAPSHOT
server: 1.593-SNAPSHOT
client: 1.0-SNAPSHOT
