### ISSUE TITLE
When trying to abort in-progress test in local gives error message as "Unable to connect to Jenkins"

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/zebrunner#2097]
Steps:
1. Open Zafira Test runs.
2. Select one or many **in-progress** test runs.
3. Click on Menu and select Abort Selected test runs.
4. verify message 

Expected result: Selected test run should get abort.
Actual result: Test showed as "Unable to connect to Jenkins"

**Comment by lmikhadyuk** [comment]
User is not able to abort a local run
