### ISSUE TITLE
Add possibility to "mark as reviewed " without comment failed/aborted test runs

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/zebrunner#2098]
**Description**
Add possibility to "mark as reviewed " without comment failed/aborted test runs

**Steps**
1. Open test runt tab
2. Click on 3 dots on passed test run
3. Select "mark as reviewed"
4. Click "mark as reviewed"

Actual result: User is able to mark as reviewed without comment only passed test runs.
Expected result: User is able to mark as reviewed without comment any test run

**Comment by DmitryMishin** [comment]
fixed on UI from v. 1.1.0.434-SNAPSHOT

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.1.0.440-SNAPSHOT server: 1.1.0.647-SNAPSHOT.
