### ISSUE TITLE
App version is absent in testrail run name

### ISSUE THREAD

**Issue by dbakhir** [zebrunner/zebrunner#2099]
Steps:
1. Run tests suite
2. Open test run in testrail

Expected result: App version is presented in testrail run name (ex. "Application version"  "Application name" - Minimal Acceptance (min_acceptance.xml) on PRODUCTION (ANDROID))

Actual result: App version is absent in testrail run name ((ex. "Application name" - Minimal Acceptance (min_acceptance.xml) on PRODUCTION (ANDROID)))

Environment:
ui: 1.38
server: 4.1.90
client: 4.1.65

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.0.0.RC2 server: 1.0.0.RC2 client: 1.0.610-SNAPSHOT.
