### ISSUE TITLE
Include information regarding testrun locale into existing\custom templates

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/zebrunner#2109]
**Description:**
 This problem is related to both Zebrunner notifications in Slack and testruns view\filters. When it comes to the project with a lots of various locales (40+), it's quite arduous to find out on which random locale\language specific test tun was executed without looking into logs, since this kind of information isn't available neither in Zebrunner notifications nor under testruns view.

**Comment by brutskov** [comment]
Test run locale will be available in test run filters since server v. 1.1.0, in slack notifications since next release (1.2.0)
