### ISSUE TITLE
"Reporting service" contains additional spaces

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#212]

**Comment by vdelendik** [comment]
@okamara, please add more details about this issue

**Comment by vdelendik** [comment]
unable to register git repository: reporting-service and open in inside jenkins correctly.
we already have several rules in nginx to redirect reporting-service traffic into the Zafira. But if it is "/jenkins/jobs/reporting-service" it should be moved to jenkins

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/zebrunner/commit/fd62cf6283c310ba089e5287bb66147e7d20ccfe

test scenario:
1) setup and start zebrunner from develo branch
2) register organization "zebrunner"
3) register repository "reporting-service" inside zebrunner folder on jenkins
4) open reporting-service folder on jenkins
-> folder is opened in jenkins
->onPush-reporting-service is red - as expected
![image](https://user-images.githubusercontent.com/4551455/90620665-6a155a00-e21b-11ea-91d1-8eafddac0d00.png)

**Comment by okamara** [comment]
Verified on release 5.2 version.Fixed.
