### ISSUE TITLE
old zafira env var naming detected

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#2127]
take a look to https://github.com/zebrunner/reporting-ui/blob/8853ffb3b1797c766eff2efa1afdba3a3cef01e3/Dockerfile#L7

and here:
https://github.com/zebrunner/reporting-ui/blob/8853ffb3b1797c766eff2efa1afdba3a3cef01e3/Dockerfile#L35

**Comment by nsidorevich** [comment]
@danymill i'll rename those variables (and i believe i can take care of UI code where those are used as well). Will contact you just in case.

**Comment by vdelendik** [comment]
@nsidorevich @danymill what do you think about having single env var? do we use both of them in front code?

**Comment by vdelendik** [comment]
also list of files where zafira-ws is detected: https://github.com/zebrunner/reporting-ui/search?q=zafira-ws&unscoped_q=zafira-ws

**Comment by nsidorevich** [comment]
@vdelendik Targeted for Zebrunner 1.4

**Comment by nsidorevich** [comment]
Released as part of 1.4
