### ISSUE TITLE
Ability to add SMTP Config Without Username / Password

### ISSUE THREAD

**Issue by maxlarochelle** [zebrunner/zebrunner#2132]
**Description**
I'm currently set-uping Zebrunner and I have a problem where the SMTP config require a username / password. My SMTP does not have one and so it is impossible to add it.

**Value**
By adding those fields optional, it will be easier to mange both user/pass SMTP and no user/pass SMTP

**Additional context**
None

**Comment by nsidorevich** [comment]
@maxlarochelle targeted for 1.4 release

**Comment by brutskov** [comment]
Will be available since server v. 1.4.0
