### ISSUE TITLE
widgets:List of values are frozen on the page after select value from drop-down

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#2159]
**Steps to reproduce**
Add a new widget e.g. APPLICATION ISSUES (BLOCKERS) DETAILS
Click "Additional fields"
Activate a field
Select value from drop-down
Scroll down
Actual result: List of values are visible on the page
**Environment**
Tested via qps-infra:develop; jenkins-master:5.1-beta3;pipeline-develop
zebrunner:
ui: 1.3.0
server: 1.3.1

**Attachments**
<img width="1208" alt="84790766-68040480-affa-11ea-9dcf-7c1e808d4fc6" src="https://user-images.githubusercontent.com/32964663/85024948-6ca5f580-b17f-11ea-9403-b2d35ac31ac1.png">

**Comment by danymill** [comment]
@lmikhadyuk Fixed on UI v. `1.6.0-RC1`

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.6.0.RC1 server: 1.6.0.RC2.
