### ISSUE TITLE
Dashboards sent by email have wrong naming convention

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/zebrunner#2172]
**Description**
Dashboards sent by email have wrong naming convention

**Steps to reproduce**
1. Open any dashboard
2. Send it by email.
3. Check the screenshot name in the email.

**Actual behavior**
1c1cfbb2-a565-4bbd-bc1f-17ef6e0f449710358673697302489308.png

**Expected behavior (if known)**
Expected name: Project Weekly Regression dashboard - 06_19_2020.pn

**Additional context**
It is a regression issue. Around a month ago everything was ok.

**Comment by lmikhadyuk** [comment]
Verified in ui: 1.8.0.9-SNAPSHOT server: 1.8.0.RC1.
