### ISSUE TITLE
views: made CI job link optional for all embedded views

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#2184]
**Description**
New TestNG agent doen't track default CI job reference for local runs.
As result all of them are not displayed in the widgets.

So we have to make this reference optional and  replace inner join by left for jobs table

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/zebrunner/commit/38f7a86ac1fdc7a7d302a18d2b3622c9d6a9178b

**Comment by okamara** [comment]
Tested by Vadim
