### ISSUE TITLE
remove nginx static content as zafira is default tool for login

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#229]
it seems like this folder is not needed anymore: https://github.com/qaprosoft/qps-infra/tree/master/nginx/html

but we have to test how mcloud/seleniub hub is displayed after removal

**Comment by vdelendik** [comment]
during testing we should ensure that
1) http://hostname - open Zafira
2) http://demo:demo@hostname/mcloud/grid/console - open mobile selenium hub (make sure static content is displayed correctly like icons, images etc)

**Comment by okamara** [comment]
Verified on qps-infra develop. Will be created a separate issue for UI page http://demo:demo@hostname/mcloud/grid/console
