### ISSUE TITLE
5.2: update docs to inform howto update crypto vars for zafira

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#230]
old location: .env.original
TOKEN_SIGNING_SECRET=AUwMLdWFBtUHVgvjFfMmAEadXqZ6HA4dKCiCmjgCXxaZ4ZO8od
CRYPTO_SALT=TDkxalR4T3EySGI0T0YyMitScmkxWDlsUXlPV2R4OEZ1b2kyL1VJeFVHST0=

new location:
reporting-service/configuration/_common/secrets.env

before updating doc sync with zebra team, maybe we can keep it in .env file for both products

**Comment by vdelendik** [comment]
token and crypto salt should be generated as part of setup process

**Comment by vdelendik** [comment]
done. token and salt might overridden as part of setup

**Comment by okamara** [comment]
Verified.

**Comment by okamara** [comment]
I don't see this information in the doc https://zebrunner.github.io/zebrunner/install-guide/

**Comment by vdelendik** [comment]
we don'n plan to describe something in documentation and setup is simple and self-descriptive
