### ISSUE TITLE
docs: add sonar integration steps for gitlab and bitbucket

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#231]
seems like integration with gitlab and bitbucket much more simple so we have to publish steps for that in config docs: https://qaprosoft.github.io/qps-infra/config-guide/#sonarqube-setup

**Comment by sandinosanchez** [comment]
done in [#355d36](https://github.com/zebrunner/zebrunner/commit/355d36132bdb8f2042bbfeed9c22a16bcd88e051)(last commit of the related docs modification)
