### ISSUE TITLE
Register Organization issues

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#232]
Env: pipeline develop,reporting-ui:1.3,JENKINS_MASTER=5.1, qps-infra - master
Steps:
1. Register Organization
2. Start Register repository
Actual result:repository is not created. Errors are present on console log

Log:
21:08:26  HttpMethod: POST 21:08:26  URL: http://reporting-service:8080/reporting-service/api/iam/v1/auth/refresh 21:08:26  Content-Type: application/json 21:08:26  Sending request to url: http://reporting-service:8080/reporting-service/api/iam/v1/auth/refresh 21:08:27  Response Code: HTTP/1.1 404  21:08:27  Success code from [200‥404]

**Comment by vdelendik** [comment]
fixed. in 1.0 (5.2-qps) release RegisterOrganization should have empty values for Service URL and token.
major note: as of now please register Service URL in short format (fix from Zafira UI is coming).
i.e. instead of
http://hostname/reporting-service
use
http://hostname

**Comment by okamara** [comment]
Tested on release version 5.2. Fixed.
