### ISSUE TITLE
.disabled file must be in .gitignore file

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/zebrunner#233]
.disabled file should be added into the .gitignore to ignore it recursively form any folder. it will be used to disable component/layer

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/qps-infra/commit/2328ffa24a62aeebdb2117c3f1bb22af7b7bd153

for testing we should 
1) run"./zebrunner.sh setup" and disable sonarqube
-> process should generate sonarqube/.disabled hidden file
2) execute below command to check if any modification detected by git:
git status
-> ideally nothing is modified

**Comment by okamara** [comment]
Tested on qps-infra develop, jenkins-5.1, pipeline-develop
I see modified files
<img width="552" alt="Screen Shot 2020-08-06 at 3 22 46 PM" src="https://user-images.githubusercontent.com/32964663/89535530-37249c80-d7ff-11ea-9a71-e0d30139b676.png">

**Comment by vdelendik** [comment]
fixed. need to remove and re-clone recursively again and setup disabling any sub-module.
.disabled, selenoid/bin/cm and selenoid/browsers.json should be displayed as modified anymore by command
`git status`

**Comment by okamara** [comment]
Verified. Fixed.

**Comment by okamara** [comment]
<img width="556" alt="Screen Shot 2020-08-17 at 2 30 07 PM" src="https://user-images.githubusercontent.com/32964663/90393298-21ce2e80-e099-11ea-910f-2b02412018e8.png">
Reporting modified files are present after disabling.

**Comment by okamara** [comment]
Reverified. Fixed.
