### ISSUE TITLE
RegisterRepository should be org/git independent

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#234]
The only benefit of the RegisterRepository per organization is that it can save git organization. At the same time if there are several control management systems like github, gitlab and/or bitbucket we can't easily register such repositories.
Also as part of the upgrade process we have to recreate RegisterRepository job per tenant.

So the goal of the ticket:
1) generate RegisterRepository job at once in management_jobs or insight for example "zebrunner (ce)" dfault folder.
2) made it GITHU_* global vars independent. I.e. I should be able to choose from global choice list any common cloud git provider and/or specify private enterprise scm url
3) it should be able to support cloning by https and ssh

Also as there is no need to generate RegisterRepository job during organization/tenant creation we can remove jobdsl object in qps-pipeline repo

**Comment by vdelendik** [comment]
done. scmType and repoUrl fields added to registerRepository job
![image](https://user-images.githubusercontent.com/4551455/96929077-3c21ef80-14c2-11eb-938a-8e0c9bd1e4f4.png)

Please, during the testing migrate carina-demo project to gitlab and bitbucket cloud and try to register them using https and ssh  repoUrl(s).
Ping me directly to setup valid integration of jenkins via ssh for above versioning cloud providers.

For now we decided to keep one global RegisterRepository job in the root and continue to generate custom RegisterRepository inside each organization. Both these jobs should be the same. The only difference is that it will automatically detect organization based on the folder where it is created.

**Comment by dhreben** [comment]
**Test scenario:**

**Bitbucket cloud HTTPS case:**

1.Sign in Bitbucket
2.Migrate carina-demo project to bitbucket cloud
3.Open Jenkins
4.Tap RegisterRepository
5.Tap Build with Parameters
6.In scmType select bitbucket
7.In repoUrl copy your carina-demo bitbucket HTTPS repository.
8.Run build and check that the build succeeded.
9.Run API-Demo-Test and check that the build succeeded.


**Expected result:** RegisterRepository build succeeded after HTTPS repoUrl(s) carina-demo project to bitbucket cloud.

<img width="939" alt="Screen Shot 2020-10-27 at 14 02 16" src="https://user-images.githubusercontent.com/50950954/97292977-0764be00-185d-11eb-844c-d7ee102b798c.png">

**Bitbucket cloud SSH case:**

1.Generate SSH on your instance `ssh-keygen`
2.nano jenkins/docker-compose.yml and add in jenkins-master - `"~/.ssh:/var/jenkins_home/.ssh"`
3.nano jenkins/docker-compose.yml and add in jenkins-slave -  - `"~/.ssh:/root/.ssh"`
4.Run `ssh -T git@bitbucket.org`
5.Sign in Bitbucket
6.Tap Personal settings
7.Tap SSH keys and add your personal SSH key
8.Open Jenkins
9.Tap RegisterRepository
10.Tap Build with Parameters
11.In scmType select bitbucket
12.In repoUrl copy your carina-demo bitbucket SSH repository.
13.Run build and check that the build succeeded.
14.Run API-Demo-Test and check that the build succeeded.

**Expected result:** RegisterRepository build succeeded after SSH repoUrl(s) carina-demo project to bitbucket cloud.



**Gitlab HTTPS case:**

1.Sign in Gitlab
2.Migrate carina-demo project to Gitlab(it is necessary to use to public project)
3.Open Jenkins
4.Tap RegisterRepository
5.Tap Build with Parameters
6.In scmType select gitlab
7.In repoUrl copy your carina-demo gitlab  HTTPS repository.
8.Run build and check that the build succeeded.
9.Run API-Demo-Test and check that the build succeeded.

   **Expected result:** RegisterRepository build succeeded after HTTPS repoUrl(s) carina-demo project to Gitlab.

<img width="942" alt="Screen Shot 2020-10-27 at 16 00 02" src="https://user-images.githubusercontent.com/50950954/97304916-7b0ec700-186d-11eb-83c5-f55648f48bbc.png">


 **Gitlab  SSH case:**
1.Generate SSH on your instance `ssh-keygen`
2.nano jenkins/docker-compose.yml and add in jenkins-master - `"~/.ssh:/var/jenkins_home/.ssh"`
3.nano jenkins/docker-compose.yml and add in jenkins-slave -  - `"~/.ssh:/root/.ssh"`
4.Run `ssh -T git@gitlab.com`
5.Sign in Gitlab
6.Tap Personal settings
7.Tap SSH keys and add your personal SSH key
8.Open Jenkins
9.Tap RegisterRepository
10.Tap Build with Parameters
11.In scmType select gitlab
12.In repoUrl copy your carina-demo bitbucket SSH repository.
13.Run build and check that the build succeeded.
14.Run API-Demo-Test and check that the build succeeded.

**Expected result:** RegisterRepository build succeeded after SSH repoUrl(s) carina-demo project to Gitlab.
