### ISSUE TITLE
docs: update install steps adding info about recursive sub-modules cloning

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#237]
1) need adjust installation steps adding valid git cloning steps with sub-module support.
it seems like such info should be updated:
git clone https://github.com/qaprosoft/qps-infra.git ...
git clone --recurse-submodule https://github.com/qaprosoft/qps-infra.git

2) ./setup.sh -> ./zebrunner.sh setup

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/commit/7ae8ed669885462401d1617a3fa051323d89a123

**Comment by okamara** [comment]
will be verified later.

**Comment by okamara** [comment]
Verified. Fixed.
