### ISSUE TITLE
Wrong branches are for sub-modules in recursive cloning of qps-infra

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#247]

**Comment by vdelendik** [comment]
valid command for cloning from scratch
git clone --recurse-submodule https://github.com/zebrunner/zebrunner.git
using custom branch:
git clone --recurse-submodule --branch "develop" https://github.com/zebrunner/zebrunner.git

for pulling recursive changes with submodules we have to run:
git pull --recurse-submodules

**Comment by okamara** [comment]
Verified on release develop branch.
