### ISSUE TITLE
Need check Gitlab and Jenkins integration  by using  usual freestyle jobs and pipeline jobs on push and pull request

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#248]

**Comment by dhreben** [comment]
The integration of Gitlab and Jenkins works correctly with freestyle and pipeline (on push and pull request) jobs.
<img width="1213" alt="Screen Shot 2020-08-17 at 13 39 48" src="https://user-images.githubusercontent.com/50950954/90510957-75597e80-e164-11ea-8050-e1a13a609962.png">
<img width="1021" alt="Screen Shot 2020-08-18 at 15 07 35" src="https://user-images.githubusercontent.com/50950954/90511060-9d48e200-e164-11ea-8529-5914130b08d1.png">

<img width="592" alt="Screen Shot 2020-08-18 at 15 10 05" src="https://user-images.githubusercontent.com/50950954/90511300-f153c680-e164-11ea-86b1-3a904f35c3ef.png">

**Comment by dhreben** [comment]
**Environment:**
 -  Jenkins-master:5.1

**Objective:**
   - Need to check Gitlab and Jenkins integration by using usual freestyle and pipeline jobs on push and pull request
 	
**Test scenario:**
1.  Open manage Jenkins >  manage plugins and install: GitLab plugins than restart Jenkins.
2.  On the main menu tap New Item.
       a. Enter the name e.g.Gitlab and tap Freestyle project.
       b. Source Code Management tap Git and enter your HTTPS project URL  from GitLab.
       c.Tick on the Build Triggers tap Build when a change is pushed to Gitlab Webhook URL and copy URL 
       d. Save project.
  3.  Open Gitlab https://gitlab.com and sign up.
  4. Tap projects and add new project e.g. carina-demo from GitHub
  5. Open carina-demo project.
        a.Tap settings >  integrations .
	b.Scroll down and choose Jenkins CI.
        с.Tick on Active.
	d.Select the events you want GitLab to trigger a Jenkins build for Push, Merge request or Tag push.
        e. Enter your freestyle project Jenkins URL  
	f. Enter your freestyle project name.
	j. Enter your Username and Password if your Jenkins server requires authentication.
	i.Click Test settings and save changes.
   6. Create a personal access token to authorize Jenkins' access to GitLab.
	a.Tap logo gitlab account.
	b.Tap settings.
	c.Tap Access Tokens.
	d.Create a personal access token with the API scope checkbox checked.
	e.Record the personal access token's value, because it's required in Configure the Jenkins server.
   7. Configure the Jenkins server:
 	a.Go to Manage Jenkins > Configure System.
	b.In the GitLab section, check the Enable authentication for /project end-point checkbox.
	c.Click Add, then choose Jenkins Credential Provider.
	d.Choose the GitLab API token as the token type.
	e.Enter the GitLab personal access token's value in the API Token field and click Add.
	f.Enter the GitLab server's URL in the GitLab host URL  field.
	j.Click Test Connection, ensuring the connection is successful before proceeding.	
   8. How to check integration:
        a. Open Gitlab https://gitlab.com  and tap your carina demo project.
	b.Tap Readme.md.
	c.Tap edit and write something.
	d.Tap commit changes.
   9. Open Jenkins and update page(you can see that build started by GitLab)
	a. Open console output and check that build success

**Comment by okamara** [comment]
Verified. Done.
