### ISSUE TITLE
update echo_help methods to use https://t.me/zebrunner

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#249]
replace everywhere qps-infra telgram channels to single Zebrunner (Community Edition) support:
 https://t.me/zebrunner

also review docs, old qps-infra.io site.

**Comment by vdelendik** [comment]
finished for zebrunner reporting: https://github.com/zebrunner/reporting/commit/675cc6e1586fa0feed870d0c7c5dfdf08876dcab
sonarqube: ???
jenkins-master: ???
mcloud: ???
selenoid: ???

**Comment by vdelendik** [comment]
done

**Comment by okamara** [comment]
1.I see that old site https://www.qps-infra.io/  is not updated yet. 
2. telegram channel is updated to https://t.me/zebrunner

**Comment by okamara** [comment]
Verified:
1. Run ./zebrunner.sh
Actual result:
<img width="521" alt="Screen Shot 2020-08-17 at 1 08 56 PM" src="https://user-images.githubusercontent.com/32964663/90384987-196ef700-e08b-11ea-8d3e-f97abc0b750a.png">
