### ISSUE TITLE
Content is not displayed correctly on UI for http://demo:demo@hostname/mcloud/grid/console

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#252]
http://demo:demo@hostname/mcloud/grid/console - open mobile selenium hub  and verify that  static content is displayed correctly like icons, images etc)

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/zebrunner/commit/a7ad8eeecea4dcaf86dc173ef6b529c6fcbca233
http://hostname/mcloud/grid/console should be loaded correctly with static content
![image](https://user-images.githubusercontent.com/4551455/90619451-f1fa6480-e219-11ea-81fc-74e5f9c0a17e.png)

**Comment by okamara** [comment]
Verified on release 5.2 version. Fixed.
