### ISSUE TITLE
Selenoid submodule contains untracked files

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#253]
Run git status in selenoid submodule:

<img width="588" alt="Screen Shot 2020-08-17 at 1 46 16 PM" src="https://user-images.githubusercontent.com/32964663/90388148-0ad70e80-e090-11ea-8839-42c54185b19e.png">

**Comment by vdelendik** [comment]
fixed, can be tested using develop branch. After setup, executing any test with video recording and even after backup - no untracked files should be detected by git

**Comment by okamara** [comment]
Verified on release version 5.2.Fixed.
