### ISSUE TITLE
Sonarqube value is not set up for Sonar URL in jenkins after default setup

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#254]
Steps:
1. Run ./zebrunner.sh setup with default values
2. Open Jenkings/ Manage Configuration and verify that Sonar URL contains value
Actual result:Sonar URL value is empty
Expected result:Sonar URL value is set up correct value

**Comment by vdelendik** [comment]
also INFRA_HOST is specified as localhost.
So use this ticket to improve jenkins common args

**Comment by vdelendik** [comment]
issue is fixed. if sonarqube is enabled we should provide valid SONAR_URL global var in jenkins.
to clone from scratch use:
git clone --recurse-submodule --branch "develop" https://github.com/zebrunner/zebrunner.git

to pull latest changes in zebrunner, branch: develop use:
git pull --recurse-submodules

**Comment by okamara** [comment]
Verified on release 5.2. Fixed.
