### ISSUE TITLE
unable to see real-time vnc session for web tests

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#255]
it seems like live vnc test artifacts is not registered using latest zafira-client. we have to identify and fix this issue

**Comment by vdelendik** [comment]
The URL 'ws://54.160.64.244:80:80/vnc/b4b8894cf09080aca034d5827a8d957e' is invalid as we concatenate web server port twice

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/zebrunner/commit/a730ca3aa9ffacbd99f0d5ab20f0c0248262bae0

**Comment by okamara** [comment]
Verified on release 5.2 version
