### ISSUE TITLE
setup default integrations based on interactive installer input

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#261]
jenkins, selenium and mcloud should be inscope of current release

**Comment by vdelendik** [comment]
done. if during setup jenkins, selenium for web and mobile enabled then in reporting such integrations should be enabled and green by default
![image](https://user-images.githubusercontent.com/4551455/90651215-6dbdd680-e245-11ea-9d6d-022206f5983e.png)

for disabled component no integration in reporting!

**Comment by okamara** [comment]
Verified on the latest release version, I haven't seen integration is working with default setup.

**Comment by okamara** [comment]
Reverified. Done
