### ISSUE TITLE
enabled/disabled layer should be saved across setup runs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#262]
we should allow to start setup process anytime. for now all input properties are stored and disaplyed from historical input.
the same approach should be organized for enabled/disabled layer.

example:
during 1st setup I disabled sonarqube. so next time I execute setup default value for "Enable Sonarqube?" should be "n".

**Comment by vdelendik** [comment]
done. changes are in develop branch.
if you enable or disable any layer/component next setup process should remember a state and provide as default value "y" or "n" accordingly

**Comment by okamara** [comment]
Verified on release 5.2. version.
