### ISSUE TITLE
Update User Guide .xml file configuration parameters list

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/zebrunner#264]
Hi, 

it appears that the list of parameters that we can put in our .xml test suite files is incomplete, since I was told that you can enable/disable video recording with the parameter "jenkinsEnableVideo", but it's not present in the page (see image): 

![image](https://user-images.githubusercontent.com/26579806/90656552-63cdb080-e210-11ea-90e2-5243f0ec9c91.png)

So it would be awesome for that list to be updated to have a clear view of everything that is possible to set in our test files to fully benefit from your incredible framework.

Thank you!
Fred

**Comment by okamara** [comment]
Additional properties are added https://github.com/zebrunner/zebrunner/blob/master/docs/user-guide.md


scheduling | This property is for running jobs by the schedule
jenkinsGroups | This property is for running jobs in accordance with testng groups annotation
jenkinsJobDisabled | This property is for disable job on Jenkins
jenkinsFailedSlackChannels | This property takes a comma separated list of slack channels to notify about failures.
jenkinsQueueRegistration | This property is a boolean parameter to manage queue registration. Disabling is recommended for suites with dynamic number of tests or dynamic test names.
jenkinsAutoScreenshot | This property is for running jobs with screenshots in test results
jenkinsEnableVideo | This property is for running jobs with video recording
provider | This property is for add provider for test job.
jenkinsNodeLabel | This property allows to override slave label and execute test on custom server
overrideFields | This property allows to add custom Fields that can override default fields.
jenkinsDefaultRetryCount | This property allows to provide custom retry_count property (number of extra attempts for test execution)

**Comment by vdelendik** [comment]
done
