### ISSUE TITLE
Zebrunner doc contains out of date image of structure

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#268]
Need to update this image for qps-infra version  5.2, zebrunner 1.0
<img width="690" alt="Screen Shot 2020-08-21 at 3 07 13 PM" src="https://user-images.githubusercontent.com/32964663/90910572-36cff800-e3e0-11ea-87db-4e27664888f0.png">

**Comment by vdelendik** [comment]
out-of-dated picture just removed: https://github.com/zebrunner/zebrunner/blob/develop/README.md

**Comment by okamara** [comment]
Fixed.
