### ISSUE TITLE
MAILING_SENDER_NAME is not populatd correctly by setup script

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#270]
email is sent using "changeit" sender name!

**Comment by vdelendik** [comment]
fixed. we should have MAILING_SENDER_NAME as SMTP_USER_NAME as of now

**Comment by dhreben** [comment]
**Verified.Done**

**Test scenario:**

1.Run ./zebrunner.sh setup   and enter:

- SMTP host :
- port :
- user:
- email:
- password:

2.Run ./zebrunner.sh start

3.Turning on 'less secure apps' settings as mail domain Administrator

4.Open Jenkins and Run:
- RegisterOrganization
- RegisterRepository
- Open e.g.API-Demo-Test and enter your email to email_list
- Tab build
5.  Build job executed successfully 
- Check your email.
<img width="1189" alt="Screen Shot 2020-08-26 at 15 05 10" src="https://user-images.githubusercontent.com/50950954/91313348-f399ce80-e7bd-11ea-91ea-8ad5fae58a76.png">
