### ISSUE TITLE
Add information about min version 1.25.5+ for docker in Guides

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#271]
Add information about min version 1.25.5+ for docker

**Comment by vdelendik** [comment]
done:
![image](https://user-images.githubusercontent.com/4551455/93355678-fdf03b00-f846-11ea-9c18-160ec8591748.png)

https://zebrunner.github.io/zebrunner/prerequisites/

**Comment by dhreben** [comment]
Verified.
