### ISSUE TITLE
add warning and extra confirmation for shutdown operation

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#273]
we have to inform user that shutdown completely destroy all settings and historical data.
Only after extra confirmation procedure should be executed.

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/91980791-7d064f00-ed30-11ea-9463-67211b82f233.png)

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/zebrunner/pull/277

**Comment by ilya-varchenya** [comment]
Test scenario:
1. Run `./zebrunner.sh shutdown`
2. You must see warning like on picture above
3. Check that script doesn't work after you enter **n**
3. Check that script work after you enter **y**

**Comment by dhreben** [comment]
Verified.
<img width="555" alt="Screen Shot 2020-09-02 at 22 03 12" src="https://user-images.githubusercontent.com/50950954/92025365-1ac94080-ed68-11ea-8744-51c9214262b3.png">
