### ISSUE TITLE
remove git integration from CE (github, gitlab and bitbucket)

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#274]
we agreed to remove git integration featire from CE reporting at all. i.e. no launchers etc and the only way to register and generate jobs: jenkins + jobdsl.
let's use this ticket to remove existing field if any in zebrunner and reporting

**Comment by vdelendik** [comment]
related pipeline tickets:
https://github.com/qaprosoft/qps-pipeline/issues/893
https://github.com/qaprosoft/qps-pipeline/issues/894
https://github.com/qaprosoft/qps-pipeline/issues/895

**Comment by vdelendik** [comment]
done. as there is no more lauchers in CE version setup process updated as well.
`Use GitHub integration for Test Launchers in Reporting UI?` question removed together with all env vars

**Comment by okamara** [comment]
Verified on zebrunner ce from dev. branch. Fixed.
