### ISSUE TITLE
unable to register jenkins integration via UI

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#275]
there is failure with loading static image: jenkins.f47ef439.svg
as result we can't register new jenkins via UI

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/zebrunner/commit/3df1133fe9b4a5a0212957e37058fd7026edf29d
1) jenkins icon should be displayed
2) functionality to register new jenkins instances workable

changes are pushed to master as a hotfix

**Comment by dhreben** [comment]
Verified

**Comment by dhreben** [comment]
Jenkins icon is not displayed
<img width="605" alt="Screen Shot 2020-10-01 at 18 38 17" src="https://user-images.githubusercontent.com/50950954/94831546-83faad00-0415-11eb-9418-6a579efc3ac8.png">

**Comment by vdelendik** [comment]
fixed
