### ISSUE TITLE
revert distributed setup support via zebrunner.sh

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#279]
setup process allow to disable component. in this case we should ask if it is installed/available on different host.
For now it seems like only url needed which should be registered in nginx default.conf only

**Comment by vdelendik** [comment]
closed as all sub-tasks finished

**Comment by vdelendik** [comment]
during testing pleaes make sure to provide external services using short protocol, host and port, i.e.
http://ip:80

**Comment by okamara** [comment]
Verified on dev. Fixed.

**Comment by vdelendik** [comment]
due to the changes for #311 this one have to be retested again! 1-2 remoted components can be tested now

**Comment by okamara** [comment]
Reverified. Done. Mcloud was reopened.

**Comment by vdelendik** [comment]
so far just commented all questions about distributed setup.
so in scope of testing please verify that for disabled components no more questions about custom url.
when done - reopen ticket again so for the next milestone we'll review and deliver this feature for all sub-components

**Comment by dhreben** [comment]
Verified with disabled components , no more questions about custom url.

**Comment by vdelendik** [comment]
final decision - do not support distributed setup via zebrunner.sh
to test - do basic acceptance using zebrunner branch: develop
no questions about custom urls for jenkins, mcloud, sonar etc
