### ISSUE TITLE
Add support "#" in setup input 

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#280]
Test case:
1. Start zebrunner setup 
2. For smtp server add password with "#"
3. Verify that password setup is successful
Expected: set up of password with "#' is successful

**Comment by vdelendik** [comment]
fixed. 
"#" symbol can be provided for any password. 
As a test scenario 
1) we shouldn't have any errors during setup execution.
2) double check that appropriate file was updated and password with special symbols registered, for example in reporting/configuration/_common/secrets.env
3) services should be started and sanity check finished

**Comment by okamara** [comment]
Not fixed.

**Comment by vdelendik** [comment]
@okamara, could you please test one more time escaping “#” symbol using back slash.
I.e. “password#” provide as “password\#”.
I’m curious if it solve the replacement by sed

**Comment by okamara** [comment]
Need to reverify together with https://github.com/zebrunner/zebrunner/issues/314

**Comment by okamara** [comment]
Fixed.
