### ISSUE TITLE
remove default nginx access and error logs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#281]
for now to inspect nginx default server logs we have to login into the nginx and tail appropriate files.
let's remove access_log and error_log declarations for default.conf to see log using "docker logs -f nginx"

https://github.com/zebrunner/zebrunner/blob/ab5500f834f2b7b89b946135be8aafecee841e8a/nginx/conf.d/default.conf.original#L17

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/zebrunner/pull/283

**Comment by ilya-varchenya** [comment]
Test scenario:
1. run Zebrunner CE
2. run command `docker logs -f nginx`
3. check that logs are not empty

**Comment by okamara** [comment]
Verified on develop, logs are not empty.
