### ISSUE TITLE
Mcloud timeout should be increased on nginx

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#285]
Now: 60
Expected:
proxy_connect_timeout   10;
     proxy_send_timeout      300;
      proxy_read_timeout      300;
      proxy_buffers           32 64m;
      proxy_buffer_size       64k;
      proxy_next_upstream    error timeout http_502 http_503 http_504;
      client_max_body_size    64m;
      client_body_buffer_size 64m;

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/commit/781e6fecd8f698af6334a60f66cac480b87be9c7

**Comment by vdelendik** [comment]
extra explanation from [#285]
For selenium/appium/selenoid under the load (10+ threads) we could detect a connection timeout error and broken sesisons:
*4967 upstream timed out (110: Connection timed out) while reading response header from upstream.

So 10 sec is not enough timeout especially if hub is remoted, it is recommended to increase to 60s by default. Successfully tested on one of the production server where we always faced with the problem.

proxy_connect_timeout - this one should be increased 10->60

**Comment by okamara** [comment]
Tested on client side. Fixed.
