### ISSUE TITLE
Create distributed setup for SonarQube

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/zebrunner#290]
This ticket is related to https://github.com/zebrunner/zebrunner/issues/279

**Comment by ilya-varchenya** [comment]
Test scenario:
1. `./zebrunner.sh setup`
2. for sonarqube choose **n**
3. after all standart packages you must see line of _Custom sonarqube_
4. for custom sonarqube choose **y**
5. enter **not your's sonarqube URL**
6. `./zebrunner.sh start`
7. go to <your_machine_ip/sonarqube>
8. check that you are redirected to custom SonarQube

Check this scenario with sonarqube's URL which contains **https**

Also check that everything will work as well with default SonarQube if you'll chose **y** on step 2

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/zebrunner/pull/289

**Comment by dhreben** [comment]
Verified
