### ISSUE TITLE
Setup secured nginx example using self-signed certificate 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#291]
Default setup of the ce should deliver self-signed certificate in dedicated ssl.conf.
By default it should redirect to http 80 port and default.conf where all location rules declared

**Comment by vdelendik** [comment]
low priority

**Comment by vdelendik** [comment]
done. testing should include verification of the:
1. presence empty nginx/ssl folder by default
2. that this folder is shared via [docker-compose.yml](https://github.com/zebrunner/zebrunner/blob/d886e2742c38010a7a0085625246dd221a77f9ad/docker-compose.yml#L13)
3. do basic acceptance using http regular setup

**Comment by okamara** [comment]
Test result:
1. .gitkeep is present in nginx/ssl 
2. passed
3. blocked now

**Comment by okamara** [comment]
Verified.
