### ISSUE TITLE
Create distributed setup for Jenkins

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/zebrunner#292]
This ticket is related to #279

Ask for custom URL for extended Jenkins.

Use info from ticket https://github.com/zebrunner/zebrunner/issues/290 as help

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/zebrunner/pull/295

**Comment by ilya-varchenya** [comment]
Test scenario as for ticket #290 but use jenkins-URLs

**Comment by okamara** [comment]
Custom jenkins url redirected to 404/500 page

**Comment by okamara** [comment]
Reverified. Fixed.
