### ISSUE TITLE
Create distributed setup for MCloud

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/zebrunner#293]
This ticket is related to #279

Ask for custom URL for extended MCloud.

Use info from ticket #290 as help

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/zebrunner/pull/296

**Comment by ilya-varchenya** [comment]
Test scenario as for ticket #290 but use MCloud-URLs

**Comment by ilya-varchenya** [comment]
Test scenario as for ticket #290 but use MCloud-URLs

**Comment by ilya-varchenya** [comment]
Need @vdelendik check

**Comment by okamara** [comment]
Tested via develop branch.
~/mcloud$ ./zebrunner.sh setup

      WARNING! Setup procedure is supported only as part of Zebrunner Server (Community Edition)!

      For more help join telegram channel: https://t.me/zebrunner

**Comment by vdelendik** [comment]
@okamara, you can test using zebrunner/zebrunner from develo branch

**Comment by okamara** [comment]
./zebrunner.sh start
for mcloud choose n
after all standart packages you must see line of Custom  mcloud
for custom  mcloud choose y
enter not your's  mcloud URL
./zebrunner.sh start
go to <your_machine_ip/mcloud>
check that you are redirected to custom mcloud
Check this scenario with mcloud's URL which contains https

Also check that everything will work as well with default mcloud if you'll chose y on step 2

**Comment by okamara** [comment]
Verified. Fixed.

**Comment by okamara** [comment]
Logic is incorrect. Need to update and retest with new logic.

**Comment by vdelendik** [comment]
closing as global task is stil under https://github.com/zebrunner/zebrunner/issues/279
