### ISSUE TITLE
Create distributed setup for Selenoid

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/zebrunner#294]
This ticket is related to #279

Ask for custom parameters for extended Selenoid.

Use info from ticket #290 as help

**Comment by ilya-varchenya** [comment]
Test scenario:
1. clone project or pull changes
2. run `./zebrunner.sh setup`
- You will need to activate jenkins and reporting service
3. Enter **n** for _Web Selenium Hub (chrome, firefox and opera)_
4. Enter some custom Selenoid url
5. run `./zebrunner.sh start`
6. go to jenkins in your browser
7. register organisation (enter url and token of your reporting service)
8. register carina-demo
9. check <your_custom_selenoid_ip>/selenoid/status (here should be some json-data)
10. run Web-demo-test job
11. check <your_custom_selenoid_ip>/selenoid/status, while test is running (json-data will be changed)
12. check for results in zebrunner
13. after test pass check <your_custom_selenoid_ip>/selenoid/status (json-data will be like in 9 step)

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/zebrunner/pull/301

**Comment by vdelendik** [comment]
merged https://github.com/zebrunner/zebrunner/pull/301

**Comment by okamara** [comment]
Verified on dev. Fixed.

**Comment by okamara** [comment]
Reverified. Fixed.
