### ISSUE TITLE
Show version of Zebrunner components

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/zebrunner#297]
Create command `./zebrunner.sh version` to show version of components

This command should show version of component, but for zebrunner (infra) it should show versions of all composite components

**Comment by ilya-varchenya** [comment]
Jenkins PR: https://github.com/zebrunner/jenkins-master/pull/287
Sonarqube PR: https://github.com/zebrunner/sonarqube/pull/22
MCloud PR: https://github.com/zebrunner/mcloud/pull/45
Selenoid PR: https://github.com/zebrunner/selenoid/pull/2
Reporting Service PR: https://github.com/zebrunner/reporting/pull/2223

**Comment by vdelendik** [comment]
merged all

**Comment by dhreben** [comment]
Verified.

<img width="589" alt="Снимок экрана 2020-09-25 в 11 15 03" src="https://user-images.githubusercontent.com/50950954/94243667-606cc980-ff20-11ea-8779-1cfd3b110dff.png">
