### ISSUE TITLE
Logs with Images are not loaded for tests

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#303]
Tested on dev branch
Steps:
1. Start jenkins
2. Create folder and repo
3. Start Web demo test
4. Open Web demo test in Reporting
Actual result: Logs with Images are not loaded for tests
<img width="920" alt="Screen Shot 2020-09-29 at 6 57 53 PM" src="https://user-images.githubusercontent.com/32964663/94583186-d2794180-0285-11eb-9a9a-47a6835279c0.png">

**Comment by vdelendik** [comment]
issue is fixed in develop branch

**Comment by okamara** [comment]
Verified on dev.
