### ISSUE TITLE
Video is not available in test report

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#304]
Tested on dev branch
Steps:
1.Start jenkins
2.Create folder and repo
3.Start Web demo test
4.Open Web demo test in Reporting
Actual result: Video is not available in test

<img width="1379" alt="Screen Shot 2020-09-29 at 6 58 00 PM" src="https://user-images.githubusercontent.com/32964663/94583780-87abf980-0286-11eb-9703-e3e60bfa7130.png">

**Comment by vdelendik** [comment]
regression issue is fixed in develo branch

**Comment by okamara** [comment]
Verified on dev.
