### ISSUE TITLE
automate "upgrade" steps for 1.0->1.1

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#305]
requirements:
1. easy way to pull latest changes recursively and apply changes in one command
```./zebrunner.sh.sh update/upgrade
```
2. existing version should be detected using ZBR_VERSION param, if absent means 1.0 
3. execute only required steps based on ZBR_VERSION, i.e. if 1.3 is applied then we should execute 1.4+ scripts
4. perform required modification steps if needed. ideally without asking any extra parameters
5. remove out-of-dated files
6. every modified file should be store in appropriate ./backup/<current_version/ folder so we could easily restore upgrade in case of any failure

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/pull/306

test scenario:
1. clone recursively using master branch
2. setup and perform sanity check (web and api jobs executed and registered)
Note: version command should display empty

4. switch to develop and do recursive pull
```
git checkout develop
git pull --recurse-submodules
```
5. try to start services
-> warn message should appear
```
You have to upgrade services in advance using: ./zebrunner.sh upgrade
```

6. upgrade service
```
./zebrunner.sh upgrade
```
7. start eveything and do sanity check

**Comment by okamara** [comment]
Verified. Fixed.
