### ISSUE TITLE
update confirm method to show valid "y/n" variant

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#307]
For now during confirm we show
Continue? Yes/No [y]:

Yes/No is rather confusing as we have to provide y or n
Let's update and display
Continue? y/n [y]:

**Comment by vdelendik** [comment]
done. you can test on develop branch during ```./zebrunner.sh setup```

**Comment by dhreben** [comment]
Verified.
<img width="777" alt="Screen Shot 2020-09-30 at 14 02 08" src="https://user-images.githubusercontent.com/50950954/94678033-892cfe80-0326-11eb-8674-64717cc3038e.png">
