### ISSUE TITLE
ask about automatic services startup after setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#308]
let's improve setup process and ask about automatic start after successful setup.
also in scope of this ticket let's remove start.sh and stop.sh at all

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/commit/6c4e9faa2d5a0535618ab3d4234680db136adccd

testing scenario:
after cloning from develop branch run setup
at the end it will ask _"Do you want to start service y/n [y]: "_
if you answer "y" services should be started

**Comment by okamara** [comment]
In the case if you answer "y" 
Actual result: services is not started
<img width="618" alt="Screen Shot 2020-09-30 at 3 46 38 PM" src="https://user-images.githubusercontent.com/32964663/94686946-35c1ad00-0334-11eb-8543-8ff151994c1c.png">

**Comment by dhreben** [comment]
Verified.
 Opened new ticket [](url)https://github.com/zebrunner/zebrunner/issues/310
