### ISSUE TITLE
Show base zebrunner folder title before shutdown started

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#309]

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/commit/b4bfa7a285b8da2e9115edd0e647a8b48179bb3e

testing scenario:
during shutdown suchwarning should appear showing valid folder where zebrunner is deployed:

```
      WARNING! Shutdown will erase all settings and data for "/home/ubuntu/tools/zebrunner"!
      Do you want to continue? y/n [n]:n
```

**Comment by okamara** [comment]
Verified on dev. Fixed.
