### ISSUE TITLE
Automatic services startup are not started after setup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#310]
Testing scenario:

Steps:
1.Cloning  Zebrunner
2.Git checkout develop
3.Run./zebrunner.sh setup
4.At the end it will ask "Do you want to start service y/n"   enter "y"

Actual result: services are not started.
Expected result: If you answer "y" services should be started.

Please see screenshot:
 <img width="675" alt="Screen Shot 2020-09-30 at 16 33 31" src="https://user-images.githubusercontent.com/50950954/94691995-b1265d00-033a-11eb-9b59-d89af8c1862b.png">

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/zebrunner/commit/600ddeb6f203614974b9c0df82c9c6991d3baad5

pull reqursivelly develop. it has default 1.1 version for users who setup from scratch

**Comment by dhreben** [comment]
fixed:
<img width="736" alt="Screen Shot 2020-09-30 at 17 47 18" src="https://user-images.githubusercontent.com/50950954/94701161-fd769a80-0344-11eb-84b3-256ae667cd30.png">
