### ISSUE TITLE
move question about starting services after start upper before configuration happen

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#311]
currently "Do you want to start service? y/n [y]:" question is displayed when selenoid part is updated.
Sometimes it is annoying when you wanna to answer "y" for everything except services startup... It is difficult to stop when selenoif is being updated

**Comment by vdelendik** [comment]
Right after S3 or minio configuration we should see such warning and question:

`Minio S3 Storage for Reporting
Enable? y/n [y]:



      WARNING! Your services needs to be started after setup.
      Start now? y/n [y]:

`

if you answer no - setup is finished without startup. if yes - configured services should be started

**Comment by dhreben** [comment]
Testing scenario:

Steps:
1.Cloning Zebrunner
2.Git checkout develop
3.Run./zebrunner.sh setup

Actual result: Automatic services startup is not started after  Start now.

Please see screenshot:
<img width="923" alt="Screen Shot 2020-10-02 at 14 20 41" src="https://user-images.githubusercontent.com/50950954/94918108-8f53e400-04ba-11eb-9b59-0262c0afc2e2.png">

**Comment by vdelendik** [comment]
root cause detected and fixed in brnach develop

**Comment by dhreben** [comment]
Fixed.
