### ISSUE TITLE
display warning for any zebrunner command if setup wasn't executed

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#312]
for any command like start/stop/restart/down/shutdown/backup/restore/upgrade/version we produce errors if setup wasn't executed.
We have to add extra verification and display single warining for any command if setup not executed yet

**Comment by vdelendik** [comment]
done. during testing just clone and execute all commands except setup one by one
-> no error messages and operations! only warning about required setup procedure is displayed and link to telegram channel

**Comment by dhreben** [comment]
Verified
