### ISSUE TITLE
Passwords are not applied after setup 

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#314]
Test case:

Start zebrunner setup
Change all possible passwords via setup ( add password with "\#")
Verify that password setup is successful in config files ,for example in reporting/configuration/_common/secrets.env
Expected: config files contain new password

**Comment by vdelendik** [comment]
https://stackoverflow.com/questions/24890230/sed-special-characters-handling

Interesting bash use-case to read all file and replace values in memory. For our small files might be very promising

**Comment by vdelendik** [comment]
fixed. all passwords during setup are applied using valid method. So we support special symbols for any password.
The only know limitation which should be published as a valid limination - unable to use double quota " symbol in the password.

During the testing use https://passwordsgenerator.net/ to generate unique credentials for every password: postres reporting and iam, rabbitmq and redis, salt crypto etc. Make sure to exclude double quota if any

Start everything and do sanity check with api and web jobs executed.

**Comment by okamara** [comment]
Tested on dev. env.
