### ISSUE TITLE
Add message that need to "start" after "backup", "restore" 

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#316]
Steps:
1. ./zebrunner.sh backup
Expected: Add message that need to "start"
2. ./zebrunner.sh start
3. ./zebrunner.sh restart
Expected: Add message that need to "start"
4. ./zebrunner.sh start

**Comment by vdelendik** [comment]
done.

**Comment by dhreben** [comment]
Verified.

Backup:

<img width="557" alt="Screen Shot 2020-11-02 at 14 01 28" src="https://user-images.githubusercontent.com/50950954/97860864-eb0cc980-1d13-11eb-9327-9ea75f3b0502.png">

Restore:

<img width="569" alt="Screen Shot 2020-11-02 at 14 05 09" src="https://user-images.githubusercontent.com/50950954/97861228-7dad6880-1d14-11eb-8ed6-c0f66f4cde27.png">
