### ISSUE TITLE
switch to 1.13RC of reporting

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#317]
integrate latest reporting and perform base sanity check.

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/commit/0f8c20f459be43d4f14904e4905fad773ad891a5

1. clone recursively zebrunner/zebrunner using develop branch.
2. verify that reporting submodule is
```
git submodule status
e2cbd1f754a38dce0043b9460ed187a29cf01262 reporting (1.12.1-13-ge2cbd1f75)
```
3. do sanity check using testlaunchers and registerrepository under custom organization
4. run api and web tests by launcher and custom org repo

**Comment by okamara** [comment]
Created a separate bug for reporting https://solvd.atlassian.net/browse/ZEB-1918

**Comment by okamara** [comment]
Tested on dev. Done.
