### ISSUE TITLE
create correct update for init.groovy.d

### ISSUE THREAD

**Issue by ilya-varchenya** [zebrunner/zebrunner#319]
After each jenkins update init.groovy.d scripts aren't chaned to newer scripts. So, we need to delete dirrectory `<jenkins_home>/init.groovy.d/*` for getting new scripts

**Comment by vdelendik** [comment]
Done as part of 1.2 upgrade steps.
Test scenario:
1. glone recursiveley using zebrunner master branch
2. Setup everythihng and execute several jobs
3. Take a look into the pipeline script for any management jobs. it begins from
`@Library('QPS-Pipeline')`
4. switch to develop branch of zebrunner and do recursive pull
5. run `./zebrunner.sh upgrade` and restart services
6. open any management job for configure
-> it should begin from
`@Library('Zebrunner-CE@develop')`

**Comment by okamara** [comment]
There are errors during upgrade:
<img width="622" alt="Screen Shot 2020-10-21 at 3 22 26 PM" src="https://user-images.githubusercontent.com/32964663/96718855-486a5780-13b1-11eb-9a23-8e3f3b6851b2.png">

**Comment by okamara** [comment]
Tested. Done.
