### ISSUE TITLE
Automatic services startup are not started

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#321]
Test scenario:

1.Git clone --recurse-submodule --branch develop 
2../zebrunner.sh setup

Actual result: Automatic services startup are not started

<img width="735" alt="Screen Shot 2020-10-21 at 17 09 18" src="https://user-images.githubusercontent.com/50950954/96731641-2a582380-13c0-11eb-815a-824dd2541c3d.png">

**Comment by vdelendik** [comment]
fixed. do recursive pull from develop and try one more time

**Comment by dhreben** [comment]
Fixed.
