### ISSUE TITLE
don't provide restart option if upgrade task failed

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#322]
Test scenario:

1.clone recursiveley using zebrunner master branch
2.Setup everythihng and execute several jobs
3.Run ./zebrunner.sh down
4.switch to develop branch of zebrunner and do recursive pull
5.run ./zebrunner.sh upgrade and start services
Actual result:Impossible ugrade or restart zebrunner after down

<img width="622" alt="Screen Shot 2020-10-21 at 3 22 26 PM" src="https://user-images.githubusercontent.com/32964663/96731904-71deaf80-13c0-11eb-8b0c-5cac69149888.png">

**Comment by vdelendik** [comment]
done. if nothing was upgraded or something failed during upgrade - we don't ask about restart.
```
ubuntu@ip-172-31-69-31:~/tools/zebrunner$ ./zebrunner.sh upgrade
      Do you want to do an upgrade? y/n [n]:y
No need to perform upgrade to 1.1
No need to perform upgrade to 1.2
No need to restart service as nothing was upgraded.
```

**Comment by okamara** [comment]
Test scenario:

1.clone recursiveley using zebrunner master branch
2.Setup everythihng and execute several jobs
3.Run ./zebrunner.sh down
4.switch to develop branch of zebrunner and do recursive pull
5.run ./zebrunner.sh upgrade and start services
Actual result:Impossible ugrade or restart zebrunner after down

<img width="638" alt="Screen Shot 2020-11-02 at 1 29 55 P@vdelendik " src="https://user-images.githubusercontent.com/32964663/97858049-a2531180-1d0f-11eb-971b-a5168493ecbc.png">

@vdelendik could you please describe test scenario for this ticket. My old scenarios is not passed.

**Comment by vdelendik** [comment]
fixed patch apply status using better approach.
so now after down any attempt to make an upgrade should fail on first patch script it applied:
```
./zebrunner.sh upgrade
      Do you want to do an upgrade? y/n [n]:y
Upgrading Zebrunner from 1.0 to 1.1
Error response from daemon: No such container: reporting-service
Error: No such container:path: postgres:/
ERROR! Unable to proceed upgrade as postgres container not available
ERROR! 1.1 patchset was not applied correctly!
```

**Comment by okamara** [comment]
Verified. Fixed.
