### ISSUE TITLE
Register repository for gitlab use github events

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#323]
Steps:
1. Change credentials in Jenkins/Change credentials for gitlab token
2. Create Organization
3. Create repository
Actual result: Console log contains events for github instead of gitlab e.g. "eventName": "x-github-event",

**Comment by sandinosanchez** [comment]
delivered in [pipeline-ce#39](https://github.com/zebrunner/pipeline-ce/pull/39/files)

The approval of this thickets depends on [pipeline-ce#5](https://github.com/zebrunner/pipeline-ce/issues/5)

**Comment by okamara** [comment]
Tested. Fixed.
