### ISSUE TITLE
setup video recording uploads using zebrunner/selenoid image with s3 support

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#324]
we use now zebrunner/selenoid:1.10.0 image which is built with s3 support: https://github.com/zebrunner/selenoid/issues/1
In this ticket we have to adjust setup process to provide valid command args or maybe variables to selenoid.
For example workable minio args are:
command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-timeout", "3m0s", "-container-network", "infra", **"-s3-endpoint", "http://minio:9000", "-s3-region", "us-east-1", "-s3-bucket-name", "zebrunner", "-s3-access-key", "zebrunner", "-s3-secret-key", "SECRETKEY", "-s3-force-path-style", "true"**]

For AWS S3 bucket args:
command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-timeout", "3m0s", "-container-network", "infra", "-s3-endpoint", "https://s3.us-east-1.amazonaws.com:443", "-s3-region", "us-east-1", "-s3-bucket-name", "NAME", "-s3-access-key", "ACCESS_KEY", "-s3-secret-key", "SECRET_KEY", "-s3-force-path-style", "true"]

Also we have to identify valid "-s3-key-pattern" to put mp4 and session log artifacts efficiently

**Comment by vdelendik** [comment]
Done. During the testing please setup integration with minio and s3 and run web-demo-test.
Important! in advance add into the overrideFields for web demo test:
carina-core_version=6.4.1024-SNAPSHOT

Expected result: video recording is available.
Extra verification: video should be uploaded to aws s3 artifacts/driver-sessions/<udid>/video.mp4

**Comment by okamara** [comment]
Tested on dev. branch. Fixed.
