### ISSUE TITLE
Public filters do not work in Zebrunner UI tool

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/zebrunner#326]
Creating a public filter in the Zebrunner test viewer does not actually make it public.

![image](https://user-images.githubusercontent.com/26579806/97574708-ff725e80-19c1-11eb-8a21-0d7c70c10382.png)

![image](https://user-images.githubusercontent.com/26579806/97574717-0305e580-19c2-11eb-8c6d-039d88b13654.png)

Here: we can't see it on another profile:

![image](https://user-images.githubusercontent.com/26579806/97574754-13b65b80-19c2-11eb-9cda-75798dad7a63.png)

**Comment by vdelendik** [comment]
some fixes were delivered in 1.40.RC3 reporting-service. Need to re-test how it works now

**Comment by okamara** [comment]
Issue is not fixed in 1.14.0 version
