### ISSUE TITLE
setup the order of the tool to be configured as default for NGiNX webserver

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#329]
for now reporting is the only tool which is configured as default entry point for NGiNX.
At the same time we have environments where it is not the true. let's provide the order of the intergation to be nabled with NGiNX if some tools are not deployed.
Order starting from high priority:
- reporting
- stf/mcloud
- jenkins
- sonaruqube
- default NGiNX page

**Comment by vdelendik** [comment]
done. testing approach is not so simple and should include set of reinstalls including shutdown. Also make sure to login to each default component and do very basic navigation inside the tool

1. setup adding general url and answer "N" for all sub-components
-> verify that only NGiNX container up&running and http://hostname display default NGiNX welcome page

2. setup again enabling only sonarqube and open http://hostname
-> it should redirect automatically to http://hostname/sonarqube and open sonar login page

3. setup again enabling only jenkins and open http://hostname
-> it should redirect automatically to http://hostname/jenkins and open jenkins login page

4. setup again enabling only mcloud and open http://hostname
-> it should redirect automatically to http://hostname/stf and open STF login page

4. setup again enabling only reporting and open http://hostname
-> it should redirect and show reporting login page

**Comment by okamara** [comment]
Fixed.
