### ISSUE TITLE
Impossible create new widget

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#331]
Steps:
1. Install zebrunner ce
2. Start
3. Create organization, repository
4. Run web demo test
5. Open reporting and create Dashboard
6. CReate a new widget 
Actual result: impossible create a new widget as user got message that widget with the same name exists
<img width="1439" alt="Screen Shot 2020-10-30 at 1 52 13 PM" src="https://user-images.githubusercontent.com/32964663/97702369-ea7bf500-1abf-11eb-813a-db2e3d5dbcb4.png">

**Comment by vdelendik** [comment]
fixed. need to get latest changes from develop and shutdown->setup->test

**Comment by okamara** [comment]
Verified. Fixed.
