### ISSUE TITLE
warn user that services will be stopped during backup/restore

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#335]
`./zebrunner.sh backup` - this command just stop services and do a backup. we have to warn user that services will be stopped and only after confirmation proceed. 
The similar stuff about restore but inform also that current data might be lost

**Comment by vdelendik** [comment]
done. during tsting make sure you can cancel or proceed with backu pand restore based on "y/n" confirmation

`ubuntu@ip-172-31-69-31:~/tools/zebrunner$ ./zebrunner.sh backup
      Your services will be stopped. Do you want to do a backup now? y/n [n]:
`

**Comment by okamara** [comment]
Tested on dev. env.
