### ISSUE TITLE
backup/restore shouldn't be started for disabled components

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#336]
inspect all sub-components but as minimal mcloud is started in disabled state

**Comment by vdelendik** [comment]
all components inspected, only mcloud didn't have verification. it is fixde now.

during the testing 
1. setup zebrunner without mcloud 
2. launch backup and restore
-> no warning/error messages about missed ftp container exists as backup/restore not even launched for disabled mcloud

**Comment by dhreben** [comment]
Fixed.
