### ISSUE TITLE
Jobs are started with errors

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#338]
Testing scenario:

clone zebrunner from master, setup everything and run regression jobs
switched to develop branch and do recurive pull
execute upgrade task
./zebrunner.sh upgrade
restart everything
Recreate Organization, Repository
Run Web Demo test or Api demo test
Actual result: Jobs are started with errors

Log:
Exception in thread "main" java.util.ServiceConfigurationError: com.sun.tools.xjc.Plugin: com.sun.tools.xjc.addon.accessors.PluginImpl Unable to get public no-arg constructor
17:27:43  	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
17:27:43  	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
17:27:43  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
17:27:43  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
17:27:43  	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
17:27:43  	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
17:27:43  	at com.sun.tools.xjc.Options.findServices(Options.java:960)
17:27:43  	at com.sun.tools.xjc.Options.getAllPlugins(Options.java:374)
17:27:43  	at com.sun.tools.xjc.Options.parseArgument(Options.java:688)
17:27:43  	at com.sun.tools.xjc.Options.parseArguments(Options.java:812)
17:27:43  	at org.jvnet.mjiip.v_2.OptionsFactory.createOptions(OptionsFactory.java:136)
17:27:43  	at org.jvnet.mjiip.v_2.OptionsFactory.createOptions(OptionsFactory.java:25)
17:27:43  	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:310)
17:27:43  	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:168)
17:27:43  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
17:27:43  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
17:27:43  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
17:27:43  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
17:27:43  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
17:27:43  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
17:27:43  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
17:27:43  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
17:27:43  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
17:27:43  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
17:27:43  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
17:27:43  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
17:27:43  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
17:27:43  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
17:27:43  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:27:43  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:27:43  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:27:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
17:27:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
17:27:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
17:27:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
17:27:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
17:27:43  Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlAccessType
17:27:43  	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
17:27:43  	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
17:27:43  	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
17:27:43  	at java.base/java.lang.Class.getConstructor(Class.java:2151)
17:27:43  	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
17:27:43  	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
17:27:43  	at java.base/java.security.AccessController.doPrivileged(Native Method)
17:27:43  	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
17:27:43  	... 34 more
17:27:43  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlAccessType

**Comment by vdelendik** [comment]
it should be fixed by releasing latest 6.5.44 carina and updating carina-demo to use jdk11 by default

**Comment by okamara** [comment]
Verified.
