### ISSUE TITLE
scmType is empty in Register repository

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#339]
Testing scenario:

clone zebrunner from master, setup everything and run regression jobs
switched to develop branch and do recurive pull
execute upgrade task
./zebrunner.sh upgrade
restart everything
Recreate Organization, 
Register Repository
Actual result: scmType is empty

**Comment by vdelendik** [comment]
jenkins upgrade task didn't register new global choices. working on it

**Comment by vdelendik** [comment]
fixed. during the upgrade it should ask about custom global choices. Answer "n" if you didn't register any custom global choices. As result they will be rplaced by new Zebrunner v1.2 and default github value shoud be in all new RegisterRepository jobs

**Comment by okamara** [comment]
Verified. Fixed.
