### ISSUE TITLE
need adjus nginx rules to load videocam_off_outlined icon from reporting

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#345]
/videocam_off_outlined.981987a2.svg conflicts with default /video redirection
![image](https://user-images.githubusercontent.com/4551455/98410229-52fd4000-2085-11eb-8426-fff94bfcc1f4.png)

**Comment by vdelendik** [comment]
fix is pretty simple and not siky so assigned to upcoming 1.2.
```
    location /video {
        root   /usr/share/nginx;
    }
```
should be replaced by 
```
    location /video/ {
        root   /usr/share/nginx;
    }

```

**Comment by vdelendik** [comment]
fixed

**Comment by okamara** [comment]
Verified on dev. env.
