### ISSUE TITLE
Update SonarQube Integration in Configuration guide

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#350]
1. Note: Compatible SonarQube version is 7.9.3 -8.0
2. Update description of SonarQube Integration with github, gitlab, bitbacket

**Comment by sandinosanchez** [comment]
done in [#355d36](https://github.com/zebrunner/zebrunner/commit/355d36132bdb8f2042bbfeed9c22a16bcd88e051)(last commit of the related docs modification)
