### ISSUE TITLE
remove external hub providers rules: browserstack/sauclebs etc

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#351]
As it is too difficult to organize optimal nginx redirect for heavy loaded systems idea to proxy all requests to external hub via nginx cancelled.
So we have to remove all rules in nginx default conf for:
aerokube
browserstack
saucelabs
zebrunner

also appropriate htpasswd files should be removed

**Comment by vdelendik** [comment]
done.
testing must include verification that mcloud grid console url require demo:deo credentials as earlier
http://hostname/mcloud/grid/console

**Comment by okamara** [comment]
Verified.
