### ISSUE TITLE
Improve documentation for Zebrunner CE

### ISSUE THREAD

**Issue by hursevich** [zebrunner/zebrunner#352]
README documentation should be updated:

1. Infrastructure scheme does not describe up to date information (at least Zafira > Zebrunner), Zebrunner components should be updated as well
2. I believe that general information from that page https://zebrunner.github.io/zebrunner/install-guide/ should be directly in README, otherwise users are not able to clone repo recursively and make the deployment successful
3. There is no information about default Zebrunner user / password to login into reporting]

**Comment by vdelendik** [comment]
done.
to test open https://github.com/zebrunner/zebrunner/blob/develop/README.md page and verify that:
1. "Initial setup" steps added. 
2. Link to detailed guide in a top of above section
3. Links and default credentials provided

**Comment by okamara** [comment]
Tested on develop branch.
