### ISSUE TITLE
Simplify Zebrunner CE setup process

### ISSUE THREAD

**Issue by hursevich** [zebrunner/zebrunner#353]
I think that configuration process is super overloaded with a lot of configuration steps:
1. I recommend to remove all the password specifications - they can be randomly generated by the script
2. We are requesting 8 cpu and 32gb ram - that makes our deployment too resource consuming for the most up to date laptops, I hope we can manage deployment in multiple components: reporting / stf / jenkins (it is scary to see 20+ containers started at once)

**Comment by vdelendik** [comment]
done.

1. reporting is obligatory part of the setup with advanced option to disable: [#381]
2. all credentials auto-generated and shown at the end (also saved in NOTICE.txt together with licensing messages)
3. LICENSE file added with Zebrunner 2018-2021 copyright
4. during secondary setup only integration settings can be updated

To test it is recommended to setup env with all components enabled, provide where possible custom settings for integrations (smtp, git, aws s3).
-> if valid integrations provided basic acceptance should pass
Run setup procedure again providing invalid integration settings aka invalid passwords
-> after restart new integrations should be applied, i.e. features should be broken (make sure to double check we don't use 1st time creds)

**Comment by okamara** [comment]
Verified.
