### ISSUE TITLE
jenkins/variables.env contain changes and should be regenerated during upgrade

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#358]
ZEBRUNNER_VERSION env variable is used to determine actual pipeline version. It is forcibly specified during restart.
During migration from 1.0 and 1.1 to 1.2 we didn't regenerate this script and as result 1.1 default pipeline version always specified.
Let's fix it in 1.3 release.
P.S. the re is no sense to fix asap because 1.1 and 1.2 pipeline releases are absolutely identical

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/commit/ead37cef0e5ed6b3c42a8f3562fedfe7fb40fd37

test scenario (upgrade use-case):
1. setup zebrunner from master (1.2v)
2. do basic acceptance
-> take a look to ./jenkins/variables.env - no ZEBRUNNER_PIPELINE variable declared inside
3. switch to develop and pull latest changes recursively
4. run `./zebrunner.sh upgrade` steps and restart everything
-> review ./jenkins/variables.env - ZEBRUNNER_PIPELINE=1.3 should be declared
5. Inspect after jenkins restart that global env var ZEBRUNNER_PIPELINE=1.3
6. run again api/web tests to make sure all good with execution

**Comment by okamara** [comment]
Ticket is blocked by https://github.com/zebrunner/zebrunner/issues/361

**Comment by vdelendik** [comment]
done, test one time
