### ISSUE TITLE
replace several system jobs during upgrade

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#359]
https://github.com/zebrunner/jenkins-master/issues/315

in root folder:
launcher
RegisterRepository

in Management_Jobs folder:
launcher
RegisterRepository
Management_Jobs/RegisterOrganization
Management_Jobs/RegisterUserCredentials
Management_Jobs/SmartJobsRerun
Management_Jobs/RegisterMavenSettings

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/commit/bcad3227c5578af0e4b981410c3c9fbd5644cfe1

as a test scenario
1. setup everything from master (1.2 release)
2. do basic acceptance test
3. switch to develop and do git recursive pull
4. perform upgrade steps `./zebrunner.sh upgrade`
-> after restarting services above jenkins jobs should have 1.3 as pipeline version. Also global env var ZEBRUNNER_PIPELINE should be updated automatically to 1.3

**Comment by okamara** [comment]
Verified, failed.
<img width="342" alt="Screen Shot 2020-11-24 at 3 47 17 PM" src="https://user-images.githubusercontent.com/32964663/100096003-6cb3cb00-2e6c-11eb-81c4-78c67846c23a.png">
Blocked by https://github.com/zebrunner/zebrunner/issues/361

**Comment by vdelendik** [comment]
fixed... try one more time

**Comment by okamara** [comment]
In global env var ZEBRUNNER_PIPELINE = https://github.com/zebrunner/pipeline-ce.git, ZEBRUNNER_VERSION =1.3

**Comment by okamara** [comment]
@vdelendik do you mean ZEBRUNNER_PIPELINE or ZEBRUNNER_VERSION in your case?

**Comment by vdelendik** [comment]
ZEBRUNNER_VERSION=1.3 of course
