### ISSUE TITLE
Repo is empty after scanning it via Launchers

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#362]
Tested on: develop branch RC build

ui: 1.16.0.RC1
server: 1.16.0.RC2

Steps:
1. Install or update zebrunner ce
2. Set up integration with Reporting
3. Register organization, repo in Jenkins
4. Run some jobs
5. Open Reporting Launcher
6. Add organization and repo carina-demo
7. Scan repo
8. Verify that Jobs are present in carina-demo repo
Actual result: carina-demo repo os empty, Register repository job is failed in jenkins
<img width="1020" alt="Screen Shot 2020-11-30 at 12 46 35 PM" src="https://user-images.githubusercontent.com/32964663/100594300-8d679f00-330a-11eb-8470-2b51067709d8.png">
<img width="1104" alt="Screen Shot 2020-11-30 at 12 46 22 PM" src="https://user-images.githubusercontent.com/32964663/100594316-90fb2600-330a-11eb-8c98-27be59d9f7bb.png">

**Comment by vdelendik** [comment]
fixed. switched to the 1.16.1.RC2 reporting-service where we expect to have a fix

**Comment by okamara** [comment]
Bug is fixed for 1 only carina-demo repo in Launcher.
