### ISSUE TITLE
remove reporting/db-migration-tool in 1.3 release

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#366]
db-migration-tool was needed obnyl to jump from qps-infra to zebrunner where we had broken changes in db.
in 1.3 migration from qps-infra 5.x is not suppoerted, i.e. you have to upgrade to zebrunner 1.0 and later apply upgrade to 1.3

**Comment by vdelendik** [comment]
done.
as a test scenario perform an upgrade. Make sure that during 1.3 patch apply db-migration-tool container and migration-tool-volume docker volume are removed, i.e. both below commands show nothing:
```
docker ps -a | grep db-migration-tool
docker volume ls | grep migration-tool-volume
```

**Comment by dhreben** [comment]
Verified. DB-migration-tool container and migration-tool-volume docker volume are removed.
