### ISSUE TITLE
Videos recorded during test execution should get saved in AWS S3 bucket.

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/zebrunner#370]
Videos recorded during test execution should get saved in AWS S3 bucket.

**Comment by vdelendik** [comment]
selenoid already have such possibility. mcloud via selenium grid will do in the same way in 1.4

**Comment by vdelendik** [comment]
done. default setup for selenoid and mcloud should publish video recording into the s3 compatible storage.
Important: web, android and ios demo tests should be executed using 
carina version: 7.0.0-SNAPSHOT
carina-demo branch: zbr-log4j2

**Comment by okamara** [comment]
Verified.
