### ISSUE TITLE
nginx logs should be limited by size

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#371]
for 1-2 months without restart our global nginx produce around 20-50Gb...
need review logging policy and setup valid rotation approach.

if possible, review also other docker container and submit enhancements

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/blob/001894f7ce3422a771a9d480cd350b76c1f474ff/docker-compose.yml#L18
To test 512Mb is too much so I recommend such approach:
1. update manually and specify "2k" which is 2048 bytes
2. start everything, do login to reporting for example
3. find path to the log file
```
docker inspect <ngix-container-id> --format='{{.LogPath}}'
/var/lib/docker/containers/e8abced5e1d7606d5fa34cb0d5744154899ba4cbbf98a71e5159b8aafd1188a6/e8abced5e1d7606d5fa34cb0d5744154899ba4cbbf98a71e5159b8aafd1188a6-json.log
```
4. using sudo track from time to time logfile size based on detected path
```
sudo ls -la /var/lib/docker/containers/e8abced5e1d7606d5fa34cb0d5744154899ba4cbbf98a71e5159b8aafd1188a6/e8abced5e1d7606d5fa34cb0d5744154899ba4cbbf98a71e5159b8aafd1188a6-json.log
```

size shouldn't be begger 2048 bytes

**Comment by dhreben** [comment]
**Test scenario:**

1..Git clone from develop
2.Run ./zebrunner.sh setup
3.nano docker-compose.yml  enter  max-size: "2k"
4.docker ps -a to find ngix-container-id
5.docker inspect ngix-container-id --format='{{.LogPath}}'
6.sudo ls -la /var/lib/docker/containers/ngix-container-id-json.log
 - -rw-r----- 1 root root **1094** Jan 16 16:39 

7.Enter to reporting
8.sudo ls -la /var/lib/docker/containers/ngix-container-id-json.log
 - -rw-r----- 1 root root **16143** Jan 16 16:41 
 
**Actual result:** Nginx logs size  begger than 2048 bytes

<img width="1305" alt="Screenshot 2021-01-16 at 20 12 46" src="https://user-images.githubusercontent.com/50950954/104818226-57896600-5837-11eb-9f8e-988dbc75807b.png">

**Comment by vdelendik** [comment]
@dhreben test one more time. after updating log size I hope you did down and start... otherwise container will use default settings

**Comment by dhreben** [comment]
Verified.
