### ISSUE TITLE
Make automation create and run nightly reporting+zebrunner ce build

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#373]
Go to https://ci.qaprosoft.com/jenkins/job/zebrunner-old/
Build -> build-ce for reporting service, iam-service, mail-service, reporting-ui 
Update reporting-service/.env
Start zebrunner ce +Smoke test

**Comment by vdelendik** [comment]
closing as invalid. @okamara please submit in private jira

**Comment by okamara** [comment]
Added jira ticket https://solvd.atlassian.net/browse/ZEB-2587
