### ISSUE TITLE
remove old ftp related data during upgrade

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#374]
https://github.com/zebrunner/mcloud/issues/71

affected files can be found here: https://github.com/zebrunner/mcloud/commit/efc20f6530e725c82cb05c1f66a4cb1944bbcf7a
Need define valid steps to remove old ftp settings from mcloud. The only question what to do with existing artifacts like video recording etc.

**Comment by vdelendik** [comment]
Implemented upgrade steps for jenkins, reporting, selenoid and mcloud.
As part of MCloud upgrade we should ask about removal old mCloud FTP volume ("n" is default answer to keep old video recordings):
```
Do you want to remove MCloud FTP data volume? You might lose old video recordings! Answer "n" to keep FTP artifacts.
```

So upgrade scenario:
1. install and zebrunner from branch master (1.3).
2. Note: it is recommended to use physical stage server where we can setup mcloud with devices
3. Run api/web/android tests (video recording should present for UI tests!)
4. Run below commands to finish upgrade (services must be up&running!)
```
cd zebrunner
git checkout develop
git pull --recurse-submodules
./zebrunner.sh upgrade
//answer "n" to keep old artifacts
```
5. after upgrade make sure you have all artifacts (screenshots/video/logs in reporting for old runs)
6. run new api/web/android tests
-> tests registered in reporting, artifacts generated and available (video, log, screenshots for ui tests)

**Comment by okamara** [comment]
Need to test on new solvd stage env. only

**Comment by vdelendik** [comment]
tested on prod
