### ISSUE TITLE
Error during setup zebrunner

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#375]
Steps:

Clone git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
Setup zebrunner
Actual result: setup log contains error message "ERROR: manifest for zebrunner/mcloud-grid:1.0-beta1 not found: manifest unknown: manifest unknown "

**Comment by vdelendik** [comment]
done.

**Comment by dhreben** [comment]
Fixed.
