### ISSUE TITLE
review and update references to selenium-hub container name using mcloud-grid

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#376]
selenium-hub container was renamed to mcloud-grid.
approperiate adjustments should be done on configuration side

**Comment by vdelendik** [comment]
done. to test 
1. setup zebrunner from develop branch
2. do recursive scan to find files with old names
```
cd zebrunner
grep -rwn . -e "selenium-hub"
```
-> no conf/yml files detected
3. test on stage that mobile android job works fine

**Comment by okamara** [comment]
will be tested after set up solvd stage env.

**Comment by dhreben** [comment]
Verified.
