### ISSUE TITLE
ask about S3 compatible storage settings if reporting not enabled

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#378]
for now mcloud can use embedded minio storage from reporting to publish artifact. At the same time we still support use-case when reporting might be disabled. In this case we have to ask about S3 compatible storage settings for mCloud component and reuse them in setup

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/zebrunner/pull/380

during the testing disable reporting and enable mcloud. it should ask about s3 compatible storage properties including optional tenant for cloud reporting integration

**Comment by okamara** [comment]
Verified.
