### ISSUE TITLE
made reporting obligatory part of the zebrunner ce

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#381]
Reporting is core part which consolidate all Test Automation Management activities and this layer should be obligatory enabled!
At the same time to support distributed setup procedure we can support tricky case to disable it by REPORTIN_DISABLED=1 env variable.

**Comment by vdelendik** [comment]
done. reporting services as a core part of the zebrunner will be enabled by default, i.e. 
-> during setup no question about enabling reporting. Question about integrations should be displayed:
```
Zebrunner General Settings
Protocol [http]:
Fully qualified domain name (ip) [152.3.125.114]:
Port [80]:
Zebrunner URL: http://152.3.125.114
Continue? y/n [y]:

Reporting SMTP Integration
Host [smtp.gmail.com]:
Port [587]:
Sender email [myemail@gmail.com]:
User [user]:
```

Scenario #2 to test for advanced way to disable reporting:
1. shutdown everything
2. declare REPORTING_DISABLED var in your current environment
```
export REPORTING_DISABLED=1
```
3. setup everything `./zebrunner.sh setup`
-> no questions about reporting services integration
-> reporting services not started
-> default `http://hostname/` url should open one of the below component (priority from high):
stf/mcloud
jenkins
sonaruqube
default NGiNX page

**Comment by okamara** [comment]
Verified.
