### ISSUE TITLE
 live VNC session is unavailable

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#382]
Steps:
1. Setup jenkins
2. Create organization/repo (qaprosoft/carina-demo)
3. Run Web-demo test
4. Verify that  live VNC session is available
Actual result:  live VNC session is unavailable
<img width="523" alt="Screen Shot 2021-01-19 at 9 13 38 PM" src="https://user-images.githubusercontent.com/32964663/105077112-12666d80-5a9d-11eb-988a-3a3bcf959f3b.png">

**Comment by vdelendik** [comment]
fixed.
to test carefully we have pull recursive and setup from scratch.
1. During testing run web-demo-test using master branch
-> live vnc session should be available
2. run webdemo-test using 6.5 branch
3. -> live vnc should be available too

**Comment by okamara** [comment]
Verified
