### ISSUE TITLE
don't put to NOTICE.txt information about empty integrations

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#383]
Reporting integration with smtp and git are optional. If no data provided we shouldn't put this data into NOTICE.txt:
```
REPORTING SERVICE INTEGRATIONS:
SMTP HOST: smtp.gmail.com:587
EMAIL:
USER: /

GIT HOST: github.com
CLIENT ID/SECRET: /
```

**Comment by vdelendik** [comment]
fixed. during setup we don't echoing to stdout and NOTICE.txt information about smtp email/user/password and git client/secret id if any of above value is empty.

During setup keep any git/smtp integration settings empty
-> no lines about smtp and/or git are displayed in console
-> no lines about smtp and/or git are displayed in NOTICE.txt

**Comment by okamara** [comment]
Verified. Fixed.
<img width="297" alt="Screen Shot 2021-01-20 at 3 10 54 PM" src="https://user-images.githubusercontent.com/32964663/105173293-dc26fd80-5b31-11eb-940e-e57fd4a9c428.png">
