### ISSUE TITLE
Broken image in Full_TestNG_HTML_Report

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#386]
Steps:
1. Open Jenkins
2. Create organization/repo
3. Start Web demo rest
4. Open Full_TestNG_HTML_Report
5. Verify that report page looks correctly
6.Actual result: Broken image near All Suites
<img width="393" alt="Screen Shot 2021-01-22 at 12 57 08 PM" src="https://user-images.githubusercontent.com/32964663/105480646-0fdf6000-5cb7-11eb-9006-1d665deb73ef.png">

Tested on 1.4.RC build for zebrunner ce

**Comment by vdelendik** [comment]
closing as won't fix. it seems like testng report/plugin issue
