### ISSUE TITLE
Register repository without folder is failed

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#387]
Tested on zebrunner 1.4_RC build on develop branch
Steps:
1. Start jenkins
2. Register repository with default params
Actual result: Register repository without folder is failed

**Comment by vdelendik** [comment]
fix pushed to the develop branch of the zebrunner, also fixed the same for upgrade scenario.
and in addition added 6th step into the [release notes](https://github.com/zebrunner/zebrunner/releases/tag/1.4) for those who has non-default organization folders:
![image](https://user-images.githubusercontent.com/4551455/105484428-584d4c80-5cbc-11eb-934a-b3fc3570f733.png)

**Comment by okamara** [comment]
Fixed.
