### ISSUE TITLE
error message during setup for disabled reporting

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#391]
export REPORTING_DISABLED=1
./zebrunner.sh setup
Zebrunner General Settings
Protocol [http]: https
Fully qualified domain name (ip) [localhost]: hostname
Port [80]: 443
Zebrunner URL: https://hostname:443
Continue? y/n [y]:
./zebrunner.sh: line 510: reporting/minio-storage/.disabled: No such file or directory

**Comment by vdelendik** [comment]
closing as can't repro

**Comment by dhreben** [comment]
Not repro.
Closed.
