### ISSUE TITLE
if reporting is disabled we have to generate ".disabled" file 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#392]
Even if reporting is disabled by env variable it tries to start everything.
.disabled file should be generated in reporting to address this issue

**Comment by vdelendik** [comment]
fixed, setup zebrunner from develop branch with disabled reporting (see #391 to remind valid steps for that).
Note: better to remove all images in advance to test step 3 below.
After startup verify that 
1. reporting/.disabled file generated
2. no reporting components up&running
3. no reporting images downloaded

**Comment by dhreben** [comment]
Fixed.
