### ISSUE TITLE
update jenkins-slave to 1.2

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#395]
https://github.com/zebrunner/jenkins-slave/milestone/3?closed=1

**Comment by dhreben** [comment]
Verified.

**Comment by vdelendik** [comment]
reopened as it was decided to upgrade jenkins components only in 1.7

**Comment by vdelendik** [comment]
done together with upgrading jenkins-master to 1.5

**Comment by okamara** [comment]
verified on dev. branch.
