### ISSUE TITLE
Test run reports from Launcher are not visible in Reporting

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#399]
Steps:
1. git clone --recurse-submodule https://github.com/zebrunner/zebrunner.git
2. Base setup
3. Start jenkins and reporting
4. Create organization and repo in jenkins
5. Open Launcher, scan default repo and run Api job or Web demo test job
Actual result: job is started but job result is not visible

Note: Launcher job is Success i Jenkins

Open Launcher Log console via jenkins:
I see a lot of warning like this ->
14:22:52  [WARNING] Could not transfer metadata io.cucumber:messages/maven-metadata.xml from/to springio-plugins-release (https://repo.spring.io/plugins-release/): Authentication failed for https://repo.spring.io/plugins-release/io/cucumber/messages/maven-metadata.xml 401 Unauthorized

**Comment by vdelendik** [comment]
closing as can't repro.

**Comment by okamara** [comment]
This issue relates to Projects. If user launch tests from Project A, he can see test runs only from All projects.

**Comment by dhreben** [comment]
Not repro.it's normal behavior.

Verified:
ui: 1.20.1
server: 1.20.1
