### ISSUE TITLE
add information about templates updates for AWS S3 storage use-case

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#405]
https://github.com/zebrunner/zebrunner/issues/403
change were delivered into the minio storage templates. the same should be done as part of the upgrade for AWS S3 as well.
Think about automating or providing as manual migration step

**Comment by vdelendik** [comment]
added as step #6 to the release notes: https://github.com/zebrunner/zebrunner/releases/tag/1.5

**Comment by okamara** [comment]
Step is added.
