### ISSUE TITLE
shutdown procedure should remove all ".disabled" files

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#406]
.disabled files are used to disable exact layer/service. During shutdown we don't remove such files as result next setup might keep them as logic exists only for it's creation.
To be able to return env into the original state we have to remove recursively all ".disabled" files or for each existing sub-component

**Comment by vdelendik** [comment]
done. as a test scenario 
1. setup with disabled as much as possible components including reporting(!).
-> verify that for every disabled sub-component ".disabled" file is generated
2. run shutdown procedure
-> all .disabled files are removed
3. run new setup enabling everything
-> previously disabled components should be up&running

**Comment by dhreben** [comment]
I can check  after fixed  https://github.com/zebrunner/zebrunner/issues/407

**Comment by dhreben** [comment]
Closed.
Opened new  ticket https://github.com/zebrunner/zebrunner/issues/411
