### ISSUE TITLE
There are not a questions about AWS S3 storage,SMTP and Github with disabled reporting after ./zebrunner.sh setup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#407]
Test scenario:

1.git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2.export REPORTING_DISABLED=1
3.`./zebrunner.sh setup` with disabled as much as possible components.
4.`./zebrunner.sh shutdown `
5.`./zebrunner.sh setup` with all enabling components

Actual result: There are not a questions about AWS S3 storage,SMTP and Github with disabled reporting after ./zebrunner.sh setup

<img width="794" alt="Screenshot 2021-02-11 at 17 36 31" src="https://user-images.githubusercontent.com/50950954/107650572-afc55380-6c8f-11eb-930d-da330175dd8d.png">

**Comment by vdelendik** [comment]
not a bug. 1st aws s3, smtp and github are reqorting related questions. No reporting - no questions...
At the end we see question for S3 because selenoid need storage

**Comment by dhreben** [comment]
Not a bug. Closed.
