### ISSUE TITLE
Zebrunner is not started correctly after Upgrade 1.0 ->1.4

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#410]
1. git clone --recurse-submodule --branch 1.0 https://github.com/zebrunner/zebrunner.git
2. ./zebrunner.sh setup
3. Create organization, repo, run Web-demo and API-demo jobs
4. git checkout develop
5. git pull --recurse-submodules
6. ./zebrunner.sh upgrade
Actual result: during setup I saw message in log
"cp: cannot stat ‘selenoid/.env’: No such file or directory "

and Jenkins is not started correctly:

"Removing rethinkdb        ... done
Network infra is external, skipping
   WARNING! You have to setup services in advance using: ./zebrunner.sh setup
   For more help join telegram channel: https://t.me/zebrunner
Stopping nginx ... done
Removing nginx ... done
Network infra is external, skipping
   WARNING! You have to upgrade services in advance using: ./zebrunner.sh upgrade
   For more help join telegram channel: https://t.me/zebrunner

TelegramTelegram
Zebrunner Support
You can view and join @zebrunner right away."

**Comment by vdelendik** [comment]
I hope fixes applied for both updades scenarion:
1.0 -> 1.5
1.4 -> 1.5

**Comment by okamara** [comment]
Fixed.
