### ISSUE TITLE
Zebrunner is not started correctly after Upgrade 1.4 ->1.5

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#412]
Steps:
git clone --recurse-submodule --branch 1.4 https://github.com/zebrunner/zebrunner.git
./zebrunner.sh setup (minio setaup)
Create organization, repo, run Web-demo and API-demo jobs
git checkout develop
git pull --recurse-submodules
./zebrunner.sh upgrade
Actual result: during setup I saw message in log
" Do you want to do an upgrade? y/n [n]:y
No need to perform upgrade to 1.1
No need to perform upgrade to 1.2
No need to perform upgrade to 1.3
No need to perform upgrade to 1.4
Upgrading Zebrunner from 1.4 to 1.5
reporting-service
SET
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
patch/1.5.sh: line 97: syntax error near unexpected token `fi'
patch/1.5.sh: line 97: `fi'
No need to restart service as nothing was upgraded.
 "

**Comment by vdelendik** [comment]
added mcloud related upgrade steps so issue should be fixed

**Comment by okamara** [comment]
Fixed.
