### ISSUE TITLE
adjust cron refresh schedule using new names and time

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#413]
in 1.20 reporting release view were renamed. that's already implemented by 045_update_views_latest_edition.sql.
At the same time during an upgrade we have to adjust cron schedules as well.
Suggested schedule so far:
SELECT cron.schedule ('1 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.LAST_32_DAYS_VIEW$$);
SELECT cron.schedule ('5 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.LAST_93_DAYS_VIEW$$);
SELECT cron.schedule ('10 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.TOTAL_VIEW$$);

**Comment by vdelendik** [comment]
done.
After 1.4->1.5 upgrade we have to ensure that new cron schedules are applied.
```
"1 0 * * *"	"REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.LAST_32_DAYS_VIEW"
"5 0 * * *"	"REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.LAST_93_DAYS_VIEW"
"10 0 * * *"	"REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.TOTAL_VIEW"
```

to review you have to follow such steps:
```
docker exec -ti postgres bash
psql -U postgres postgres
select * from cron.job;
```
make sure 3 above views with exact the same schedule are registered

**Comment by okamara** [comment]
Fixed
