### ISSUE TITLE
Documents page for carina is broken 

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#415]
Open http://qaprosoft.github.io/carina from https://github.com/okamara/carina-demo
Actual result: Documents page is broken
<img width="1430" alt="Screen Shot 2021-02-15 at 11 02 27 AM" src="https://user-images.githubusercontent.com/32964663/107920117-75083780-6f7d-11eb-9036-eda9dadc67e7.png">

**Comment by vdelendik** [comment]
fixed.

**Comment by okamara** [comment]
Fixed.
