### ISSUE TITLE
onPush job is failed during create repo in Zebrunner 1.0

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#416]
Steps:
1. git clone --recurse-submodule --branch 1.0 https://github.com/zebrunner/zebrunner.git
2. Zebrunner setup
3. Start zebrunner
4. Register organization
5. Register repo
Actual result: register repo is failed, onPush job is failed.
<img width="1091" alt="Screen Shot 2021-02-15 at 12 10 44 PM" src="https://user-images.githubusercontent.com/32964663/107928756-c9b1af80-6f89-11eb-908d-9a3dea8b3b3a.png">

**Comment by vdelendik** [comment]
not a bug. @okamara for all releases <1.4 we have to scan/run "6.5" branch of the qaprosoft/carina-demo as ony this branch is compatible with java8.
