### ISSUE TITLE
Sql errors during upgrade zebrunner from 1.0 to 1.5

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#417]
git clone --recurse-submodule --branch 1.0 https://github.com/zebrunner/zebrunner.git
./zebrunner.sh setup
Create organization, repo, run Web-demo and API-demo jobs
git checkout develop
git pull --recurse-submodules
./zebrunner.sh upgrade
Actual result: during upgrade I saw message in log

psql:/tmp/reporting-1.20-db-migration.sql:3893: ERROR: syntax error at or near “#”
LINE 1: #413: adjust cron refresh schedule using new names and time
    ^
psql:/tmp/reporting-1.20-db-migration.sql:3894: ERROR: relation “job” does not exist
LINE 1: DELETE FROM JOB;
          ^
 schedule

**Comment by vdelendik** [comment]
fix delievered into the develop branch

**Comment by okamara** [comment]
Fixed.
