### ISSUE TITLE
Zebrunner setup is started instead of  zebrunner start in upgrade process

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#418]
git clone --recurse-submodule --branch 1.0 https://github.com/zebrunner/zebrunner.git
./zebrunner.sh setup
Create organization, repo, run Web-demo and API-demo jobs
git checkout develop
git pull --recurse-submodules
./zebrunner.sh upgrade
Actual result: during upgrade I saw zebrunner setup instead of start

./zebrunner.sh shutdown
Actual result: during shutdown I saw zebrunner setup 
<img width="652" alt="Screen Shot 2021-02-15 at 2 25 24 PM" src="https://user-images.githubusercontent.com/32964663/107940925-084f6600-6f9a-11eb-9266-948877a35e76.png">

**Comment by vdelendik** [comment]
closing as won't fix. these messages inside the logs are not so important. Fixes might produce serious regression issues in regular functionality
