### ISSUE TITLE
Manifest error during setup zebrunner

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#422]
**Test scenario:**

1.Clone git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2.`./zebrunner.sh setup`

**Actual result:** ERROR: manifest for zebrunner/reporting-service:1.21.0.116-SNAPSHOT not found: manifest unknown: manifest unknown

<img width="845" alt="Screenshot 2021-02-25 at 19 11 36" src="https://user-images.githubusercontent.com/50950954/109181762-597f0700-779d-11eb-9662-e4ac29cce0f1.png">

**Comment by dhreben** [comment]
To resolve this issue need change version build to  1.21.0.146-SNAPSHOT

**Comment by vdelendik** [comment]
fixed putting valid version of reporting-service into the develop branch

**Comment by dhreben** [comment]
Fixed
