### ISSUE TITLE
Zafira report contains n/a value

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#423]
Verified on Zebrunner ce 14

Steps:
1. Set up zebrunner
2. Create organization qaprosoft
3. Create repo
4. Run Api demo test and Web demo test jobs
5. Verify Zafira reports for these jobs
6.Actual result: Zafira report contains n/a value (see image)
<img width="1420" alt="Screen Shot 2021-02-26 at 1 46 49 PM" src="https://user-images.githubusercontent.com/32964663/109293881-7834da80-783d-11eb-8919-2a5257769a19.png">

**Comment by vdelendik** [comment]
already exists in reoprting. closing as dupe
