### ISSUE TITLE
regenerate selenoid .env during an upgrade to 1.6

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#424]
details: https://github.com/zebrunner/selenoid/issues/15

**Comment by vdelendik** [comment]
done.
test scenario should include 
1. setup from master (v1.5)
2. sanity test
3. swicth to develop branch and pull recursively
4. `./zebrunner.sh upgrade`
5. sanity test with attention to web job results

**Comment by dhreben** [comment]
Verified.
