### ISSUE TITLE
"Bad message 431" is in logs of jobs

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#426]
Steps:
1. Clone zebrunner from develop branch
2. Set up zebrunner(minio)
3. Register organization qaprosoft
4. Register repo
5. Start API, Web demo job
6. Actual result: "Bad message 431" is in logs of jobs
Note: when job is completed all log is visible without Bad message

**Comment by vdelendik** [comment]
closing as can't reproduce on latest env from develop

**Comment by okamara** [comment]
Can't repro after cleaning cookies
