### ISSUE TITLE
regenerate mcloud/.env during upgrade to 1.6

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#430]
mcloud/.env.original was changed (new mcloud-grid version added).
we have to regenerate mcloud/.env if enabled during upgrade

**Comment by vdelendik** [comment]
fixed. test using default upgrade scenario:
1. setup everything from zebrunner, branch: master
2. do basic acceptance
Note: it supposed to have problems with connecting android/ios devices (as designed)
3. switch to develop branch, do recursive pull and upgrade
```
cd ./zebrunner
git checkout develop
git pull --recurse-submodules
//make sure to have mcloud (1.6) for
git submodule status
./zebrunner.sh upgrade
```
4. Verify that new zebrunner/stf:1.1 is used as part of the mcloud components
5. Verify that mcloud-android and mcloud-ios could be registered and used successfully according to latest instructions from their master branches

**Comment by dhreben** [comment]
Verified.
