### ISSUE TITLE
widget templates still has reference to the "task" field

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#432]
1. APPLICATION ISSUES (BLOCKERS) DETAILS widget template can't be generated as it has TASK in query by default
2. TESTS EXECUTION ROI (MAN-HOURS) and PASS RATE (BAR) has TASK among filter.

During the testing 
1. install and setup from master (i.e. 1.5 release). 
2. Run api and we tests.
3. upgrade to the latest from develop branch
4. run again api and web
5. generate new board and create 3 widgets for above templates:
-> widgets can be generate without any failures (no error message in right bottom corner)
-> no "TASK" filter displayed

**Comment by vdelendik** [comment]
fix delivered: https://github.com/zebrunner/zebrunner/commit/c128ad0e3bba1f5bd72c110dfbc7c96e126ef86a
test scenario described in the bug description

**Comment by dhreben** [comment]
Fixed.
