### ISSUE TITLE
upgrade: bump up to the new version of widget templates

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#434]
blocker feature was removed from reporting keeping it only in jira only. so we have to apply widget and widget templates changes during update.
detailes of the reporting changes: https://gitlab.com/zebrunner/ce/reporting-service/-/merge_requests/201

**Comment by vdelendik** [comment]
templates changes:
APPLICATION ISSUES (BLOCKERS) COUNTrename to "APPLICATION ISSUES COUNT"remove BLOCKER param, if logic and params sample 

APPLICATION ISSUES (BLOCKERS) DETAILSrename to "APPLICATION ISSUES DETAILS"desc to "Detailed information about known issues."remove BLOCKER param, if logic and params sample 

TESTS FAILURES BY REASONremove BLOCKER param, if logic and params sample

**Comment by vdelendik** [comment]
still blocked as mine PR not merged to reporting service yet: https://gitlab.com/zebrunner/ce/reporting-service/-/merge_requests/201
some changes on back-end side still required

**Comment by vdelendik** [comment]
adjusted subject as we got new generation of widget templates where all templates where adjusted. So in scope of upgrade we have to patch/rename all affected templates in management schema

**Comment by vdelendik** [comment]
whole list of changes can be reviewed here: https://github.com/zebrunner/reporting/commit/a27c816741bd0a7cab68e6588188896e1b38bc29

**Comment by vdelendik** [comment]
done: new version of widget templates should be applied as part of upgrade scenario.

1. clone and setup zebrunner from master branch (pre-upgrade scenario)
2. run full_regression to register set of jobs
3. switch into the develop and do recursive pull
````
git checkout develop
git pull --recurse-submodules
./zebrunner.sh upgrade
```
4. after restart review all default boards/widgets and try to generate new widgets based on every template (all of them were reorganized in scope of current release)

**Comment by okamara** [comment]
verified, fixed.
