### ISSUE TITLE
remove jenkinsEnableVideo suite parameter from user guide

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#439]
we don't need it anymore: https://github.com/zebrunner/pipeline-ce/issues/134
we are going to enable it by default for our own hub providers. Users might manage this capabilities later on their own using capabilities, overrideFields or custom fields if needed

**Comment by vdelendik** [comment]
fixed. ticket better to verify before the release right after merging to master. It should update official docs on github.io

**Comment by okamara** [comment]
Will be tested later.

**Comment by dhreben** [comment]
Fixed.
