### ISSUE TITLE
during shutdown minio-storage_miniodata-volume is removed twice

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#441]
Network infra is external, skipping
Removing volume minio-storage_miniodata-volume
Network infra is external, skipping
Removing volume minio-storage_miniodata-volume
WARNING: Volume minio-storage_miniodata-volume not found.

**Comment by vdelendik** [comment]
fixed. during shutdown we should run removal at once, i.e. no WARN anymore in console logs.
Also please test scenario for #411 as potentially current change might restore this problem.

**Comment by dhreben** [comment]
Fixed.

Reopened.#411
