### ISSUE TITLE
bump up to jankins-master 1.5

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#445]
new jenkins-master is coming with set of improvements into the pipelines and new plugins/versions/slaves

**Comment by vdelendik** [comment]
done. setup from scratch using zebrunner branch: develop should have 1.5 jenkins-master and 1.5 pipeline version inside

**Comment by okamara** [comment]
Verified on zebrunner ce dev. branch. Smoke test is done.
