### ISSUE TITLE
Previous pipeline version is not working, need to update pipeline version till 1.5

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#446]
Preconditions:
git clone and setup zebrunner from dev branch

Steps:
1. Create organization qaprosoft
2. Register rero carina-demo
3. Run API test job
Actual result: Tests can't be started
Log:

"15:46:11  2021-05-31 12:46:11 Reflections [main-1] [INFO] Reflections took 929 ms to scan 9 urls, producing 2352 keys and 11447 values 
15:46:11  2021-05-31 12:46:11 FilterTestsListener [main-1] [INFO] There are no any rules and limitations
15:46:11  [ERROR] Could not register start of the test run.
15:46:11  Response status code: 404.
15:46:11  Raw response body: 
15:46:11  {"code":"REP-2032","message":"Requested project can not be found by name 'unknown'"}
15:46:11  [INFO] 
15:46:11  [INFO] Results:
15:46:11  [INFO] 
15:46:11  [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
15:46:11  [INFO] 
15:46:11  [ERROR] There are test failures."

**Comment by vdelendik** [comment]
closing as dupe of #445
