### ISSUE TITLE
upgrade: replace management jobs by new content

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#447]
during 1.7->1.8 migration it is planned to switch management_jobs to use master branch of the pipeline.
https://github.com/zebrunner/jenkins-master/pull/339/files#diff-a9ce8bf5fb6262283374a622897da0cbe7904632e640fbea3fe9d8ae194f36b0L37

**Comment by vdelendik** [comment]
done.
to test 
1. clone and setup zebrunner from master (upgrade scenario)
2. take a look into the Management_Jobs/*** syntax (pipeline versions inside might be hardcoded and pretty old aka 1.2-1.4
3. perform upgrade scenarion pulling recursively using develop zebrunner brnach
4. run `./zebrunner.sh upgrade`
5. after services restart review all management_jobs/*** syntax. Everywhere `@Library('Zebrunner-CE@master')` should be declated in the top of pipeline syntax.
6. do basic acceptance running as much as possible management_jobs

**Comment by okamara** [comment]
Verified, Fixed.
