### ISSUE TITLE
remove all docs related to git integration and laucnhers

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#451]
original ticket is [#274]

**Comment by vdelendik** [comment]
done, whole githu oauth block removed form prerequisited:
![image](https://user-images.githubusercontent.com/4551455/121246677-1824ea00-c8aa-11eb-9283-2a89a92aaed4.png)

It might be tested only after merging from develop to master

**Comment by dhreben** [comment]
Verified.
