### ISSUE TITLE
put into the migration steps info about renaming zafira_project to reporting.project-key

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#453]
During this release we stop to support old zafira agent and as result `zafira_project` property inside each TestNG xml suite should be renamed obligatory to `reporting.project-key`.
Requirements obligatory for those who use pro version of the reporting as in ce projects support is removed completely

**Comment by vdelendik** [comment]
that's a readme for CE where this property is not actual anymore and might be omitted

**Comment by dhreben** [comment]
Not actual .
Closed.
