### ISSUE TITLE
upgrade: remove all cron expressions and register new one

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#456]
during the upgrade only such cron expressions should exist:
https://github.com/zebrunner/reporting/issues/2295

**Comment by vdelendik** [comment]
done.
follow upgrade scenarion and review that after `upgrade` task execution cron table has only 2 lines with values described in reporting ticket above

**Comment by okamara** [comment]
Verified after upgrade. Fuxed.
Run:
 docker exec -ti postgres bash 
and 
psql -U postgres postgres
set schema 'cron';
select * from job;
<img width="1025" alt="Снимок экрана 2021-06-22 в 14 40 43" src="https://user-images.githubusercontent.com/32964663/122918511-df841680-d367-11eb-826e-2ac1e0a58180.png">
