### ISSUE TITLE
upgrade: regenerate zebrunner-proxy nginx.conf

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#458]
zebrunner-proxy nginx.conf.original is updated in 1.24 release.
during new setup it should be auto-populated automatically but as part of the upgrade we have to replace it from .original. It seems like no changes inside but anyway let's create a backup.

**Comment by vdelendik** [comment]
done. patch/1.8.sh script should regenerate zebrunner-proxy/nginx.conf using original.

test scenario:
1. clone and setup zebrunner from **master** branch (pre-upgrade scenario)
2. run full_regression to register set of jobs
3. switch into the develop and do recursive pull
```
git checkout develop
git pull --recurse-submodules
./zebrunner.sh upgrade
```
4. after services restart login into the reporting and review web tests
-> runs and tests should be opened successfully
-> screenshots should be available
5. run more jobs to test that screenshots might be registered on new version as well

**Comment by okamara** [comment]
Verified. Fixed.
