### ISSUE TITLE
migration: explain in advance that projects and launchers functionality will be removed during the upgrade

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#462]
project labels can't be supported anymore in CE part as well as launchers (git integration).
we have to explain this info in release doc to clarify that some data might be lost after upgrade

**Comment by vdelendik** [comment]
fixed
![image](https://user-images.githubusercontent.com/4551455/123787110-1bc4f300-d8e3-11eb-93f4-9c4f90ad7052.png)

**Comment by dhreben** [comment]
Verified.
