### ISSUE TITLE
upgrade: adjust 2 widgets on the general board

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#464]
two widgets on general boards should be adjusted as no more project field available.
1st, `30 DAYS PASS RATE BY PROJECT (%)` should be renamed to `30 DAYS PASS RATE BY OWNER (%)`
and group by `OWNER` specified

2nd, `30 DAYS TEST DETAILS` should be groupped by OWNER and RUN_NAME legend should be disabled

**Comment by vdelendik** [comment]
done.
after upgrade visit General board and check that requested changes exist and data is displayed correctly

**Comment by okamara** [comment]
Verified, fixed.
