### ISSUE TITLE
Needed additional RabbitMQ queues for holding CI test run requests from external tools

### ISSUE THREAD

**Issue by SergeiZagriychuk** [zebrunner/zebrunner#73]
The idea is to use RabbitMQ as proxy layer for accessing of Jenkins instances if they're hidden under vpn (how it currently works for mfp web infra)
Flow is next:
1) External service publishes new run requests to RabbitMQ queue (with some unique ci_run_id)
2) Jenkins gets messages from the queue with some scheduling
3) Jenkins executes new run if there are valid requests in the queue and marks RabbitMQ message as acknowledged
4) After execution is done Jenkins publishes results into another queue; published message contains ci_run_id for identification of particular run.
Note: Step 4 is needed to handle results of execution in external tools (e.g. some CI tool)

Going forward solution could be integrated with zafira. So there could be an option to queue new test run from Zafira for Jenkins which is hidden under vpn

In order to implement the solution I need 2 new RabbitMQ queues.
Names could something like ciRunsQueue and ciRunResultsQueue

**Comment by vdelendik** [comment]
already established using customized solution
